
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_pak

REPO = Path(__file__).resolve().parent.parent.parent

GEN_ROOT = REPO / "generated"
OUT = GEN_ROOT / (sys.argv[sys.argv.index("--package") + 1]
                  if "--package" in sys.argv else "red")

BANNER = """/* GENERATED by tools/assetpack/gen_bindings.py, do not edit.
 *
 * Regenerate:  pwsh tools/py.ps1 tools/assetpack/gen_bindings.py
 */
"""

def _decl(a):
    if a.get("ctype"):
        return f"const {a['ctype']} *{a['name']}"
    if a["elem"]:
        return f"const {a.get('elem_type', 'uint8_t')} (*{a['name']}){a['elem']}"
    return f"const uint8_t *{a['name']}"

def main():
    bound = [a for a in build_pak.ASSETS if a["bind"]]
    OUT.mkdir(parents=True, exist_ok=True)

    h = [BANNER, "#pragma once", "#include <stdint.h>", "#include <stdbool.h>"]

    for hdr in sorted({a["ctype_header"] for a in bound if a.get("ctype_header")}):
        h.append(f'#include "{hdr}"')
    h.append("")
    h.append("/* Bind every cut-over asset from the open pack. Call once at boot,")
    h.append(" * AFTER AssetPack_Open. Aborts with a clear message if the pack is")
    h.append(" * missing an asset this build needs -- a silent NULL here would")
    h.append(" * surface as a crash deep inside rendering instead. */")
    h.append("void AssetPack_BindAll(void);")
    h.append("")
    for a in bound:
        h.append("extern " + _decl(a) + ";")
        h.append(f"extern uint32_t {a['name']}_count;")
    h.append("")
    h.append('#include "data/music_types.h"')
    h.append("/* Music: filled by AssetPack_BindAll. Each channel keeps the")
    h.append(" * name it had as a static in the old generated header, so the")
    h.append(" * player's song table needs no change. */")
    for stem, ch in build_pak.MUSIC_CHANNELS:
        h.append(f"extern ch_data_t k{stem}_Ch{ch};")
    h.append(f"extern drum_inst_t kDrumInst"
             f"[{build_pak.NUM_DRUM_INSTRUMENTS + 1}];")
    h.append("extern const uint8_t *kMapMusicID;")
    h.append("extern uint32_t kMapMusicID_count;")
    h.append("")
    h.append("/* Variable-length records: pointer arrays rebuilt at boot from")
    h.append(" * a blob plus an offset table. Non-const so BindAll can fill")
    h.append(" * them; the POINTED-AT bytes are const, which is what call sites")
    h.append(" * actually rely on. */")
    h.append(f"extern const uint8_t *gEvosMoves"
             f"[{build_pak.EVOS_MOVES_TABLE_SIZE}];")
    h.append(f"extern const uint8_t *gTrainerPartyData"
             f"[{build_pak.NUM_TRAINERS}];")
    h.append(f"extern const uint8_t *gMoveAnimAttackAnimationPointers"
             f"[{build_pak.MOVE_ANIM_NUM_ATTACK_ANIMS}];")
    h.append("/* Name tables: the same blob + offsets shape, but the strings")
    h.append(" * are char rather than byte runs, so these are char pointers.")
    h.append(" * The port indexes them exactly as before. */")
    h.append(f"extern const char *gMoveNames[{build_pak.NUM_MOVE_NAMES}];")
    h.append(f"extern const char *gTrainerClassNames"
             f"[{build_pak.NUM_TRAINER_NAMES}];")
    h.append("")
    h.append('#include "data/move_anim_frameblocks.h"')
    h.append('#include "game/battle/move_anim.h"')
    h.append("/* Same idea, but the elements are DESCRIPTORS -- a count (and for")
    h.append(" * subanimations a type) beside a pointer into the blob. BindAll")
    h.append(" * builds those descriptors; see the loop that fills them. */")
    h.append(f"extern const move_anim_frameblock_def_t"
             f" *gMoveAnimFrameBlockPointers[{build_pak.MOVE_ANIM_NUM_FRAMEBLOCKS}];")
    h.append(f"extern const subanim_def_t"
             f" *gMoveAnimSubanimationPointers[{build_pak.MOVE_ANIM_NUM_SUBANIMS}];")
    h.append("")
    h.append('#include "data/cry_types.h"')
    h.append("/* Cry definitions: the note POINTERS are filled by BindAll, so")
    h.append(" * the array itself is non-const. The notes are const. */")
    h.append(f"extern cry_def_t g_cry_defs[{build_pak.NUM_BASE_CRIES}];")
    h.append("")

    c = [BANNER, '#include "assetpack_bind.h"',
         '#include "platform/assetpack.h"']

    for hdr in sorted({a["ctype_header"] for a in bound if a.get("ctype_header")}):
        c.append(f'#include "{hdr}"')
    c.append("")
    for a in bound:
        c.append(_decl(a) + ";")
        c.append(f"uint32_t {a['name']}_count;")
    c.append("")
    for stem, ch in build_pak.MUSIC_CHANNELS:
        c.append(f"ch_data_t k{stem}_Ch{ch};")
    c.append(f"drum_inst_t kDrumInst[{build_pak.NUM_DRUM_INSTRUMENTS + 1}];")
    c.append("const uint8_t *kMapMusicID;")
    c.append("uint32_t kMapMusicID_count;")
    c.append(f"const uint8_t *gEvosMoves[{build_pak.EVOS_MOVES_TABLE_SIZE}];")
    c.append(f"const uint8_t *gTrainerPartyData[{build_pak.NUM_TRAINERS}];")
    c.append(f"const uint8_t *gMoveAnimAttackAnimationPointers"
             f"[{build_pak.MOVE_ANIM_NUM_ATTACK_ANIMS}];")
    c.append(f"const char *gMoveNames[{build_pak.NUM_MOVE_NAMES}];")
    c.append(f"const char *gTrainerClassNames[{build_pak.NUM_TRAINER_NAMES}];")
    c.append(f"const move_anim_frameblock_def_t"
             f" *gMoveAnimFrameBlockPointers[{build_pak.MOVE_ANIM_NUM_FRAMEBLOCKS}];")
    c.append(f"const subanim_def_t"
             f" *gMoveAnimSubanimationPointers[{build_pak.MOVE_ANIM_NUM_SUBANIMS}];")
    c.append(f"cry_def_t g_cry_defs[{build_pak.NUM_BASE_CRIES}];")
    c.append("")

    tilesets = list(range(build_pak.NUM_TILESETS))
    if tilesets:
        c.append('#include "data/tileset_data.h"   /* tileset_info_t */')
        c.append("")
        c.append("/* NOT const: filled in at boot. Every consumer reads it")
        c.append(" * through a `const tileset_info_t *`, so this is invisible")
        c.append(" * to them. */")
        c.append("tileset_info_t gTilesets[NUM_TILESETS];")
        c.append("")

    c.append('#include "data/map_data.h"   /* map_info_t, NUM_MAPS */')
    c.append("")
    c.append("map_info_t gMapTable[NUM_MAPS];")
    c.append("")
    c.append("/* Debug labels + amberscript's name-based vmap lookup. Not ROM")
    c.append(" * content, so they live here rather than in the pack. */")
    c.append("static const char *const kMapNames[NUM_MAPS] = {")
    for i in range(0, build_pak.NUM_MAPS, 4):
        row = ", ".join('"%s"' % build_pak.MAP_NAMES[j]
                        for j in range(i, min(i + 4, build_pak.NUM_MAPS)))
        c.append(f"    {row},")
    c.append("};")
    c.append("")

    c.append("/* 1 = an UNUSED map id that repeats a real map's name/blocks")
    c.append(" * (MAP_FILLER in build_pak.py). Forward lookups may use these;")
    c.append(" * a name->id lookup MUST skip them or it resolves the wrong")
    c.append(" * map -- see Map_RealIdForName. */")
    c.append("const uint8_t gMapIsFillerId[NUM_MAPS] = {")
    for i in range(0, build_pak.NUM_MAPS, 16):
        row = ", ".join(str(1 if j in build_pak.MAP_FILLER else 0)
                        for j in range(i, min(i + 16, build_pak.NUM_MAPS)))
        c.append(f"    {row},")
    c.append("};")
    c.append("")

    c.append("void AssetPack_BindAll(void)")
    c.append("{")
    if not bound and not tilesets:
        c.append("    /* nothing cut over yet */")
    for a in bound:
        if a.get("ctype"):
            cast = f"const {a['ctype']} *"
        elif a["elem"]:
            cast = f"const {a.get('elem_type', 'uint8_t')} (*){a['elem']}"
        else:
            cast = "const uint8_t *"
        c.append(f"    {a['name']} = ({cast})"
                 f"AssetPack_Require(\"{a['name']}\", &{a['name']}_count);")

    if tilesets:
        c.append("")
        c.append("    {")
        c.append("        AssetPack_Entry blocks, gfx, coll;")
        c.append("        const uint8_t *ga = (const uint8_t *)"
                 "AssetPack_Require(\"gTilesetGrassAnim\", NULL);")
        c.append("        const uint8_t *ct = (const uint8_t *)"
                 "AssetPack_Require(\"gTilesetCounterTiles\", NULL);")
        c.append("        #define BIND_TILESET(i, B, G, C) \\")
        c.append("            AssetPack_Find(B, &blocks); \\")
        c.append("            AssetPack_Find(G, &gfx); \\")
        c.append("            AssetPack_Find(C, &coll); \\")
        c.append("            gTilesets[i].blocks     = (const uint8_t *)blocks.data; \\")
        c.append("            gTilesets[i].num_blocks = (uint16_t)blocks.count; \\")
        c.append("            gTilesets[i].gfx        = (const uint8_t *)gfx.data; \\")
        c.append("            gTilesets[i].gfx_tiles  = (uint16_t)gfx.count; \\")
        c.append("            gTilesets[i].coll_tiles = (const uint8_t *)coll.data; \\")
        c.append("            gTilesets[i].grass_tile = ga[(i) * 2]; \\")
        c.append("            gTilesets[i].anim_type  = ga[(i) * 2 + 1]; \\")
        c.append("            gTilesets[i].counter[0] = ct[(i) * 3]; \\")
        c.append("            gTilesets[i].counter[1] = ct[(i) * 3 + 1]; \\")
        c.append("            gTilesets[i].counter[2] = ct[(i) * 3 + 2]")
        for idx in tilesets:
            b, g, co = (build_pak.tileset_asset_name(idx, s) for s in range(3))
            c.append(f'        BIND_TILESET({idx}, "{b}", "{g}", "{co}");')
        c.append("        #undef BIND_TILESET")
        c.append("    }")

    c.append("")
    c.append("    {")
    c.append("        const uint8_t *meta = (const uint8_t *)"
             "AssetPack_Require(\"gMapMeta\", NULL);")
    c.append("        AssetPack_Entry b;")
    c.append("        int i;")
    c.append("        for (i = 0; i < NUM_MAPS; i++) {")
    c.append("            gMapTable[i].width        = meta[i * 4 + 0];")
    c.append("            gMapTable[i].height       = meta[i * 4 + 1];")
    c.append("            gMapTable[i].tileset_id   = meta[i * 4 + 2];")
    c.append("            gMapTable[i].border_block = meta[i * 4 + 3];")
    c.append("            gMapTable[i].blocks       = NULL;")
    c.append("            gMapTable[i].name         = kMapNames[i];")
    c.append("        }")
    c.append("        /* Unused map IDs share a real map's blocks -- see")
    c.append("         * MAP_FILLER in build_pak.py. */")
    c.append("        #define BIND_MAP(i, key) \\")
    c.append("            if (AssetPack_Find(key, &b)) \\")
    c.append("                gMapTable[i].blocks = (const uint8_t *)b.data")
    for i in range(build_pak.NUM_REAL_MAPS):
        key = build_pak.map_asset_name(build_pak.map_blocks_source(i))
        c.append(f'        BIND_MAP({i}, "{key}");')
    c.append("        #undef BIND_MAP")
    c.append("    }")

    c.append("")
    c.append("    {")
    c.append("        AssetPack_Entry e;")
    c.append("        const uint8_t *loops = (const uint8_t *)"
             "AssetPack_Require(\"gMusicChannelLoops\", NULL);")
    c.append("        #define BIND_CH(sym, key, i) \\")
    c.append("            AssetPack_Find(key, &e); \\")
    c.append("            sym.notes = (const note_evt_t *)e.data; \\")
    c.append("            sym.count = (int)e.count; \\")
    c.append("            sym.loop_start = (int)(int16_t)"
             "((uint16_t)loops[(i) * 2] | ((uint16_t)loops[(i) * 2 + 1] << 8))")
    for i, (stem, ch) in enumerate(build_pak.MUSIC_CHANNELS):
        key = build_pak.channel_asset_name(stem, ch)
        c.append(f'        BIND_CH(k{stem}_Ch{ch}, "{key}", {i});')
    c.append("        #undef BIND_CH")
    c.append("")
    c.append("        #define BIND_DRUM(i, key) \\")
    c.append("            AssetPack_Find(key, &e); \\")
    c.append("            kDrumInst[i].steps = (const drum_step_t *)e.data; \\")
    c.append("            kDrumInst[i].count = (uint8_t)e.count")
    c.append("        kDrumInst[0].steps = NULL; kDrumInst[0].count = 0;")
    for i in range(1, build_pak.NUM_DRUM_INSTRUMENTS + 1):
        c.append(f'        BIND_DRUM({i}, "kDrumInst{i}_steps");')
    c.append("        #undef BIND_DRUM")
    c.append("")
    c.append("        kMapMusicID = (const uint8_t *)"
             "AssetPack_Require(\"kMapMusicID\", &kMapMusicID_count);")
    c.append("    }")

    c.append("")
    c.append("    {")
    c.append("        const uint8_t *blob;")
    c.append("        const uint8_t *offs;")
    c.append("        uint32_t n;")
    c.append("        int i;")
    c.append("        #define BIND_PTRS(table, blobkey, offkey) \\")
    c.append("            blob = (const uint8_t *)AssetPack_Require(blobkey, NULL); \\")
    c.append("            offs = (const uint8_t *)AssetPack_Require(offkey, &n); \\")
    c.append("            for (i = 0; i < (int)n; i++) { \\")
    c.append("                uint16_t o = (uint16_t)((uint16_t)offs[i * 2] | "
             "((uint16_t)offs[i * 2 + 1] << 8)); \\")
    c.append(f"                table[i] = (o == {build_pak.NO_ENTRY}u) "
             f"? NULL : blob + o; \\")
    c.append("            }")
    c.append('        BIND_PTRS(gEvosMoves, "gEvosMovesBlob", "gEvosMovesOffsets");')
    c.append('        BIND_PTRS(gTrainerPartyData, "gTrainerPartyBlob", "gTrainerPartyOffsets");')
    c.append('        BIND_PTRS(gMoveAnimAttackAnimationPointers,'
             ' "gMoveAnimScriptBlob", "gMoveAnimScriptOffsets");')
    c.append("        #define BIND_STRS(table, blobkey, offkey) \\")
    c.append("            blob = (const uint8_t *)AssetPack_Require(blobkey, NULL); \\")
    c.append("            offs = (const uint8_t *)AssetPack_Require(offkey, &n); \\")
    c.append("            for (i = 0; i < (int)n; i++) { \\")
    c.append("                uint16_t o = (uint16_t)((uint16_t)offs[i * 2] | "
             "((uint16_t)offs[i * 2 + 1] << 8)); \\")
    c.append("                table[i] = (const char *)(blob + o); \\")
    c.append("            }")
    c.append('        BIND_STRS(gMoveNames, "gMoveNamesBlob",'
             ' "gMoveNamesOffsets");')
    c.append('        BIND_STRS(gTrainerClassNames, "gTrainerClassNamesBlob",'
             ' "gTrainerClassNamesOffsets");')
    c.append("        #undef BIND_STRS")
    c.append("        #undef BIND_PTRS")
    c.append("    }")

    c.append("")
    c.append("    _Static_assert(sizeof(sfx_def_t) == 4,")
    c.append('                   "gSfxDefs is a packed memory image from the '
             'pack: bank, channel_count, chan_first");')
    c.append("    _Static_assert(sizeof(sfx_channel_t) == 6,")
    c.append('                   "gSfxChannels is a packed memory image: '
             'hw_channel, pad, cmd_first, cmd_count");')
    c.append("    _Static_assert(sizeof(move_sfx_cmd_t) == 10,")
    c.append('                   "gSfxCmds is a packed memory image: type, '
             'pad, then four int16");')
    c.append("    _Static_assert(sizeof(move_sfx_data_t) == 4,")
    c.append('                   "gMoveSfxData is a packed memory image: '
             'sfx_index, pitch_mod, tempo_mod");')

    c.append("")
    c.append("    _Static_assert(sizeof(move_anim_frameblock_sprite_t) == 6,")
    c.append('                   "frame block sprites are read in place from the '
             'pack blob; the struct must stay 6 packed bytes");')
    c.append("    _Static_assert(sizeof(subanim_entry_t) == 3,")
    c.append('                   "subanimation entries are read in place from the '
             'pack blob; the struct must stay 3 packed bytes");')
    c.append("")
    c.append("    {")
    c.append("        const uint8_t *blob, *offs;")
    c.append("        uint32_t n;")
    c.append("        int i;")
    c.append("")
    c.append(f"        static move_anim_frameblock_def_t"
             f" s_fb[{build_pak.MOVE_ANIM_NUM_FRAMEBLOCKS}];")
    c.append('        blob = (const uint8_t *)AssetPack_Require("gMoveAnimFrameBlockBlob", NULL);')
    c.append('        offs = (const uint8_t *)AssetPack_Require("gMoveAnimFrameBlockOffsets", &n);')
    c.append("        for (i = 0; i < (int)n; i++) {")
    c.append("            uint16_t o = (uint16_t)((uint16_t)offs[i * 2] |"
             " ((uint16_t)offs[i * 2 + 1] << 8));")
    c.append("            s_fb[i].count   = blob[o];")
    c.append("            s_fb[i].sprites = (const move_anim_frameblock_sprite_t *)(blob + o + 1);")
    c.append("            gMoveAnimFrameBlockPointers[i] = &s_fb[i];")
    c.append("        }")
    c.append("")
    c.append(f"        static subanim_def_t s_sa[{build_pak.MOVE_ANIM_NUM_SUBANIMS}];")
    c.append('        blob = (const uint8_t *)AssetPack_Require("gMoveAnimSubanimBlob", NULL);')
    c.append('        offs = (const uint8_t *)AssetPack_Require("gMoveAnimSubanimOffsets", &n);')
    c.append("        for (i = 0; i < (int)n; i++) {")
    c.append("            uint16_t o = (uint16_t)((uint16_t)offs[i * 2] |"
             " ((uint16_t)offs[i * 2 + 1] << 8));")
    c.append("            s_sa[i].type    = blob[o];")
    c.append("            s_sa[i].count   = blob[o + 1];")
    c.append("            s_sa[i].entries = (const subanim_entry_t *)(blob + o + 2);")
    c.append("            gMoveAnimSubanimationPointers[i] = &s_sa[i];")
    c.append("        }")
    c.append("    }")

    c.append("")
    c.append("    {")
    c.append("        const cry_sq_note_t *sq = (const cry_sq_note_t *)"
             "AssetPack_Require(\"g_cry_sq_notes\", NULL);")
    c.append("        const cry_noise_note_t *nz = (const cry_noise_note_t *)"
             "AssetPack_Require(\"g_cry_noise_notes\", NULL);")
    c.append("        const uint8_t *m = (const uint8_t *)"
             "AssetPack_Require(\"g_cry_defs_meta\", NULL);")
    c.append("        int i;")
    c.append(f"        for (i = 0; i < {build_pak.NUM_BASE_CRIES}; i++) {{")
    c.append(f"            const uint8_t *e = m + i * {build_pak.CRY_META_BYTES};")
    c.append("            g_cry_defs[i].ch5.duty_pattern = e[0];")
    c.append("            g_cry_defs[i].ch5.rotate_duty  = e[1];")
    c.append("            g_cry_defs[i].ch5.n_notes      = e[2];")
    c.append("            g_cry_defs[i].ch5.notes        = sq + "
             "((uint16_t)e[3] | ((uint16_t)e[4] << 8));")
    c.append("            g_cry_defs[i].ch6.duty_pattern = e[5];")
    c.append("            g_cry_defs[i].ch6.rotate_duty  = e[6];")
    c.append("            g_cry_defs[i].ch6.n_notes      = e[7];")
    c.append("            g_cry_defs[i].ch6.notes        = sq + "
             "((uint16_t)e[8] | ((uint16_t)e[9] << 8));")
    c.append("            g_cry_defs[i].ch8.n_notes      = e[10];")
    c.append("            g_cry_defs[i].ch8.notes        = nz + "
             "((uint16_t)e[11] | ((uint16_t)e[12] << 8));")
    c.append("        }")
    c.append("    }")
    c.append("}")
    c.append("")

    (OUT / "assetpack_bind.h").write_text("\n".join(h), encoding="utf-8")
    (OUT / "assetpack_bind.c").write_text("\n".join(c), encoding="utf-8")

    print(f"wrote generated/assetpack_bind.{{h,c}}  ({len(bound)} bound asset(s))")
    for a in bound:
        print(f"  {a['name']}{a['elem']}")

if __name__ == "__main__":
    main()
