
#pragma once
#include <stdint.h>

typedef struct {
    uint8_t        channel;
    uint16_t       entry;
    uint16_t       len;
    const uint8_t *data;
} crystal_audio_channel_t;

typedef struct {
    const char *name;
    uint8_t     num_channels;
    const crystal_audio_channel_t *channels;
} crystal_audio_track_t;

#define CRYSTAL_NUM_MUSIC 103
#define CRYSTAL_NUM_SFX 207
#define CRYSTAL_NUM_CRIES 68

#define CRYSTAL_MUSIC_NONE                         0
#define CRYSTAL_MUSIC_TITLE                        1
#define CRYSTAL_MUSIC_ROUTE_1                      2
#define CRYSTAL_MUSIC_ROUTE_3                      3
#define CRYSTAL_MUSIC_ROUTE_12                     4
#define CRYSTAL_MUSIC_MAGNET_TRAIN                 5
#define CRYSTAL_MUSIC_KANTO_GYM_LEADER_BATTLE      6
#define CRYSTAL_MUSIC_KANTO_TRAINER_BATTLE         7
#define CRYSTAL_MUSIC_KANTO_WILD_BATTLE            8
#define CRYSTAL_MUSIC_POKEMON_CENTER               9
#define CRYSTAL_MUSIC_HIKER_ENCOUNTER              10
#define CRYSTAL_MUSIC_LASS_ENCOUNTER               11
#define CRYSTAL_MUSIC_OFFICER_ENCOUNTER            12
#define CRYSTAL_MUSIC_HEAL                         13
#define CRYSTAL_MUSIC_LAVENDER_TOWN                14
#define CRYSTAL_MUSIC_ROUTE_2                      15
#define CRYSTAL_MUSIC_MT_MOON                      16
#define CRYSTAL_MUSIC_SHOW_ME_AROUND               17
#define CRYSTAL_MUSIC_GAME_CORNER                  18
#define CRYSTAL_MUSIC_BICYCLE                      19
#define CRYSTAL_MUSIC_HALL_OF_FAME                 20
#define CRYSTAL_MUSIC_VIRIDIAN_CITY                21
#define CRYSTAL_MUSIC_CELADON_CITY                 22
#define CRYSTAL_MUSIC_TRAINER_VICTORY              23
#define CRYSTAL_MUSIC_WILD_VICTORY                 24
#define CRYSTAL_MUSIC_GYM_VICTORY                  25
#define CRYSTAL_MUSIC_MT_MOON_SQUARE               26
#define CRYSTAL_MUSIC_GYM                          27
#define CRYSTAL_MUSIC_PALLET_TOWN                  28
#define CRYSTAL_MUSIC_POKEMON_TALK                 29
#define CRYSTAL_MUSIC_PROF_OAK                     30
#define CRYSTAL_MUSIC_RIVAL_ENCOUNTER              31
#define CRYSTAL_MUSIC_RIVAL_AFTER                  32
#define CRYSTAL_MUSIC_SURF                         33
#define CRYSTAL_MUSIC_EVOLUTION                    34
#define CRYSTAL_MUSIC_NATIONAL_PARK                35
#define CRYSTAL_MUSIC_CREDITS                      36
#define CRYSTAL_MUSIC_AZALEA_TOWN                  37
#define CRYSTAL_MUSIC_CHERRYGROVE_CITY             38
#define CRYSTAL_MUSIC_KIMONO_ENCOUNTER             39
#define CRYSTAL_MUSIC_UNION_CAVE                   40
#define CRYSTAL_MUSIC_JOHTO_WILD_BATTLE            41
#define CRYSTAL_MUSIC_JOHTO_TRAINER_BATTLE         42
#define CRYSTAL_MUSIC_ROUTE_30                     43
#define CRYSTAL_MUSIC_ECRUTEAK_CITY                44
#define CRYSTAL_MUSIC_VIOLET_CITY                  45
#define CRYSTAL_MUSIC_JOHTO_GYM_LEADER_BATTLE      46
#define CRYSTAL_MUSIC_CHAMPION_BATTLE              47
#define CRYSTAL_MUSIC_RIVAL_BATTLE                 48
#define CRYSTAL_MUSIC_ROCKET_BATTLE                49
#define CRYSTAL_MUSIC_PROF_ELM                     50
#define CRYSTAL_MUSIC_DARK_CAVE                    51
#define CRYSTAL_MUSIC_ROUTE_29                     52
#define CRYSTAL_MUSIC_ROUTE_36                     53
#define CRYSTAL_MUSIC_SS_AQUA                      54
#define CRYSTAL_MUSIC_YOUNGSTER_ENCOUNTER          55
#define CRYSTAL_MUSIC_BEAUTY_ENCOUNTER             56
#define CRYSTAL_MUSIC_ROCKET_ENCOUNTER             57
#define CRYSTAL_MUSIC_POKEMANIAC_ENCOUNTER         58
#define CRYSTAL_MUSIC_SAGE_ENCOUNTER               59
#define CRYSTAL_MUSIC_NEW_BARK_TOWN                60
#define CRYSTAL_MUSIC_GOLDENROD_CITY               61
#define CRYSTAL_MUSIC_VERMILION_CITY               62
#define CRYSTAL_MUSIC_POKEMON_CHANNEL              63
#define CRYSTAL_MUSIC_POKE_FLUTE_CHANNEL           64
#define CRYSTAL_MUSIC_TIN_TOWER                    65
#define CRYSTAL_MUSIC_SPROUT_TOWER                 66
#define CRYSTAL_MUSIC_BURNED_TOWER                 67
#define CRYSTAL_MUSIC_LIGHTHOUSE                   68
#define CRYSTAL_MUSIC_LAKE_OF_RAGE                 69
#define CRYSTAL_MUSIC_INDIGO_PLATEAU               70
#define CRYSTAL_MUSIC_ROUTE_37                     71
#define CRYSTAL_MUSIC_ROCKET_HIDEOUT               72
#define CRYSTAL_MUSIC_DRAGONS_DEN                  73
#define CRYSTAL_MUSIC_JOHTO_WILD_BATTLE_NIGHT      74
#define CRYSTAL_MUSIC_RUINS_OF_ALPH_RADIO          75
#define CRYSTAL_MUSIC_CAPTURE                      76
#define CRYSTAL_MUSIC_ROUTE_26                     77
#define CRYSTAL_MUSIC_MOM                          78
#define CRYSTAL_MUSIC_VICTORY_ROAD                 79
#define CRYSTAL_MUSIC_POKEMON_LULLABY              80
#define CRYSTAL_MUSIC_POKEMON_MARCH                81
#define CRYSTAL_MUSIC_GS_OPENING                   82
#define CRYSTAL_MUSIC_GS_OPENING_2                 83
#define CRYSTAL_MUSIC_MAIN_MENU                    84
#define CRYSTAL_MUSIC_RUINS_OF_ALPH_INTERIOR       85
#define CRYSTAL_MUSIC_ROCKET_OVERTURE              86
#define CRYSTAL_MUSIC_DANCING_HALL                 87
#define CRYSTAL_MUSIC_BUG_CATCHING_CONTEST_RANKING 88
#define CRYSTAL_MUSIC_BUG_CATCHING_CONTEST         89
#define CRYSTAL_MUSIC_LAKE_OF_RAGE_ROCKET_RADIO    90
#define CRYSTAL_MUSIC_PRINTER                      91
#define CRYSTAL_MUSIC_POST_CREDITS                 92
#define CRYSTAL_MUSIC_CLAIR                        93
#define CRYSTAL_MUSIC_MOBILE_ADAPTER_MENU          94
#define CRYSTAL_MUSIC_MOBILE_ADAPTER               95
#define CRYSTAL_MUSIC_BUENAS_PASSWORD              96
#define CRYSTAL_MUSIC_MYSTICALMAN_ENCOUNTER        97
#define CRYSTAL_MUSIC_CRYSTAL_OPENING              98
#define CRYSTAL_MUSIC_BATTLE_TOWER_THEME           99
#define CRYSTAL_MUSIC_SUICUNE_BATTLE               100
#define CRYSTAL_MUSIC_BATTLE_TOWER_LOBBY           101
#define CRYSTAL_MUSIC_MOBILE_CENTER                102

#define CRYSTAL_SFX_DEX_FANFARE_50_79              0
#define CRYSTAL_SFX_ITEM                           1
#define CRYSTAL_SFX_CAUGHT_MON                     2
#define CRYSTAL_SFX_POKEBALLS_PLACED_ON_TABLE      3
#define CRYSTAL_SFX_POTION                         4
#define CRYSTAL_SFX_FULL_HEAL                      5
#define CRYSTAL_SFX_MENU                           6
#define CRYSTAL_SFX_READ_TEXT                      7
#define CRYSTAL_SFX_READ_TEXT_2                    8
#define CRYSTAL_SFX_DEX_FANFARE_20_49              9
#define CRYSTAL_SFX_DEX_FANFARE_80_109             10
#define CRYSTAL_SFX_POISON                         11
#define CRYSTAL_SFX_GOT_SAFARI_BALLS               12
#define CRYSTAL_SFX_BOOT_PC                        13
#define CRYSTAL_SFX_SHUT_DOWN_PC                   14
#define CRYSTAL_SFX_CHOOSE_PC_OPTION               15
#define CRYSTAL_SFX_ESCAPE_ROPE                    16
#define CRYSTAL_SFX_PUSH_BUTTON                    17
#define CRYSTAL_SFX_SECOND_PART_OF_ITEMFINDER      18
#define CRYSTAL_SFX_WARP_TO                        19
#define CRYSTAL_SFX_WARP_FROM                      20
#define CRYSTAL_SFX_CHANGE_DEX_MODE                21
#define CRYSTAL_SFX_JUMP_OVER_LEDGE                22
#define CRYSTAL_SFX_GRASS_RUSTLE                   23
#define CRYSTAL_SFX_FLY                            24
#define CRYSTAL_SFX_WRONG                          25
#define CRYSTAL_SFX_SQUEAK                         26
#define CRYSTAL_SFX_STRENGTH                       27
#define CRYSTAL_SFX_BOAT                           28
#define CRYSTAL_SFX_WALL_OPEN                      29
#define CRYSTAL_SFX_PLACE_PUZZLE_PIECE_DOWN        30
#define CRYSTAL_SFX_ENTER_DOOR                     31
#define CRYSTAL_SFX_SWITCH_POKEMON                 32
#define CRYSTAL_SFX_TALLY                          33
#define CRYSTAL_SFX_TRANSACTION                    34
#define CRYSTAL_SFX_EXIT_BUILDING                  35
#define CRYSTAL_SFX_BUMP                           36
#define CRYSTAL_SFX_SAVE                           37
#define CRYSTAL_SFX_POKEFLUTE                      38
#define CRYSTAL_SFX_ELEVATOR_END                   39
#define CRYSTAL_SFX_THROW_BALL                     40
#define CRYSTAL_SFX_BALL_POOF                      41
#define CRYSTAL_SFX_FAINT                          42
#define CRYSTAL_SFX_RUN                            43
#define CRYSTAL_SFX_SLOT_MACHINE_START             44
#define CRYSTAL_SFX_FANFARE                        45
#define CRYSTAL_SFX_PECK                           46
#define CRYSTAL_SFX_KINESIS                        47
#define CRYSTAL_SFX_LICK                           48
#define CRYSTAL_SFX_POUND                          49
#define CRYSTAL_SFX_MOVE_PUZZLE_PIECE              50
#define CRYSTAL_SFX_COMET_PUNCH                    51
#define CRYSTAL_SFX_MEGA_PUNCH                     52
#define CRYSTAL_SFX_SCRATCH                        53
#define CRYSTAL_SFX_VICEGRIP                       54
#define CRYSTAL_SFX_RAZOR_WIND                     55
#define CRYSTAL_SFX_CUT                            56
#define CRYSTAL_SFX_WING_ATTACK                    57
#define CRYSTAL_SFX_WHIRLWIND                      58
#define CRYSTAL_SFX_BIND                           59
#define CRYSTAL_SFX_VINE_WHIP                      60
#define CRYSTAL_SFX_DOUBLE_KICK                    61
#define CRYSTAL_SFX_MEGA_KICK                      62
#define CRYSTAL_SFX_HEADBUTT                       63
#define CRYSTAL_SFX_HORN_ATTACK                    64
#define CRYSTAL_SFX_TACKLE                         65
#define CRYSTAL_SFX_POISON_STING                   66
#define CRYSTAL_SFX_POWDER                         67
#define CRYSTAL_SFX_DOUBLESLAP                     68
#define CRYSTAL_SFX_BITE                           69
#define CRYSTAL_SFX_JUMP_KICK                      70
#define CRYSTAL_SFX_STOMP                          71
#define CRYSTAL_SFX_TAIL_WHIP                      72
#define CRYSTAL_SFX_KARATE_CHOP                    73
#define CRYSTAL_SFX_SUBMISSION                     74
#define CRYSTAL_SFX_WATER_GUN                      75
#define CRYSTAL_SFX_SWORDS_DANCE                   76
#define CRYSTAL_SFX_THUNDER                        77
#define CRYSTAL_SFX_SUPERSONIC                     78
#define CRYSTAL_SFX_LEER                           79
#define CRYSTAL_SFX_EMBER                          80
#define CRYSTAL_SFX_BUBBLEBEAM                     81
#define CRYSTAL_SFX_HYDRO_PUMP                     82
#define CRYSTAL_SFX_SURF                           83
#define CRYSTAL_SFX_PSYBEAM                        84
#define CRYSTAL_SFX_CHARGE                         85
#define CRYSTAL_SFX_THUNDERSHOCK                   86
#define CRYSTAL_SFX_PSYCHIC                        87
#define CRYSTAL_SFX_SCREECH                        88
#define CRYSTAL_SFX_BONE_CLUB                      89
#define CRYSTAL_SFX_SHARPEN                        90
#define CRYSTAL_SFX_EGG_BOMB                       91
#define CRYSTAL_SFX_SING                           92
#define CRYSTAL_SFX_HYPER_BEAM                     93
#define CRYSTAL_SFX_SHINE                          94
#define CRYSTAL_SFX_UNKNOWN_5F                     95
#define CRYSTAL_SFX_UNKNOWN_60                     96
#define CRYSTAL_SFX_UNKNOWN_61                     97
#define CRYSTAL_SFX_SWITCH_POCKETS                 98
#define CRYSTAL_SFX_UNKNOWN_63                     99
#define CRYSTAL_SFX_BURN                           100
#define CRYSTAL_SFX_TITLE_SCREEN_ENTRANCE          101
#define CRYSTAL_SFX_UNKNOWN_66                     102
#define CRYSTAL_SFX_GET_COIN_FROM_SLOTS            103
#define CRYSTAL_SFX_PAY_DAY                        104
#define CRYSTAL_SFX_METRONOME                      105
#define CRYSTAL_SFX_CALL                           106
#define CRYSTAL_SFX_HANG_UP                        107
#define CRYSTAL_SFX_NO_SIGNAL                      108
#define CRYSTAL_SFX_SANDSTORM                      109
#define CRYSTAL_SFX_ELEVATOR                       110
#define CRYSTAL_SFX_PROTECT                        111
#define CRYSTAL_SFX_SKETCH                         112
#define CRYSTAL_SFX_RAIN_DANCE                     113
#define CRYSTAL_SFX_AEROBLAST                      114
#define CRYSTAL_SFX_SPARK                          115
#define CRYSTAL_SFX_CURSE                          116
#define CRYSTAL_SFX_RAGE                           117
#define CRYSTAL_SFX_THIEF                          118
#define CRYSTAL_SFX_THIEF_2                        119
#define CRYSTAL_SFX_SPIDER_WEB                     120
#define CRYSTAL_SFX_MIND_READER                    121
#define CRYSTAL_SFX_NIGHTMARE                      122
#define CRYSTAL_SFX_SNORE                          123
#define CRYSTAL_SFX_SWEET_KISS                     124
#define CRYSTAL_SFX_SWEET_KISS_2                   125
#define CRYSTAL_SFX_BELLY_DRUM                     126
#define CRYSTAL_SFX_TOXIC                          127
#define CRYSTAL_SFX_SLUDGE_BOMB                    128
#define CRYSTAL_SFX_FORESIGHT                      129
#define CRYSTAL_SFX_SPITE                          130
#define CRYSTAL_SFX_OUTRAGE                        131
#define CRYSTAL_SFX_PERISH_SONG                    132
#define CRYSTAL_SFX_GIGA_DRAIN                     133
#define CRYSTAL_SFX_ATTRACT                        134
#define CRYSTAL_SFX_KINESIS_2                      135
#define CRYSTAL_SFX_ZAP_CANNON                     136
#define CRYSTAL_SFX_MEAN_LOOK                      137
#define CRYSTAL_SFX_HEAL_BELL                      138
#define CRYSTAL_SFX_RETURN                         139
#define CRYSTAL_SFX_EXP_BAR                        140
#define CRYSTAL_SFX_MILK_DRINK                     141
#define CRYSTAL_SFX_PRESENT                        142
#define CRYSTAL_SFX_MORNING_SUN                    143
#define CRYSTAL_SFX_LEVEL_UP                       144
#define CRYSTAL_SFX_KEY_ITEM                       145
#define CRYSTAL_SFX_FANFARE_2                      146
#define CRYSTAL_SFX_REGISTER_PHONE_NUMBER          147
#define CRYSTAL_SFX_3RD_PLACE                      148
#define CRYSTAL_SFX_GET_EGG_UNUSED                 149
#define CRYSTAL_SFX_GET_EGG                        150
#define CRYSTAL_SFX_MOVE_DELETED                   151
#define CRYSTAL_SFX_2ND_PLACE                      152
#define CRYSTAL_SFX_1ST_PLACE                      153
#define CRYSTAL_SFX_CHOOSE_A_CARD                  154
#define CRYSTAL_SFX_GET_TM                         155
#define CRYSTAL_SFX_GET_BADGE                      156
#define CRYSTAL_SFX_QUIT_SLOTS                     157
#define CRYSTAL_SFX_EGG_CRACK                      158
#define CRYSTAL_SFX_DEX_FANFARE_LESS_THAN_20       159
#define CRYSTAL_SFX_DEX_FANFARE_140_169            160
#define CRYSTAL_SFX_DEX_FANFARE_170_199            161
#define CRYSTAL_SFX_DEX_FANFARE_200_229            162
#define CRYSTAL_SFX_DEX_FANFARE_230_PLUS           163
#define CRYSTAL_SFX_EVOLVED                        164
#define CRYSTAL_SFX_MASTER_BALL                    165
#define CRYSTAL_SFX_EGG_HATCH                      166
#define CRYSTAL_SFX_GS_INTRO_CHARIZARD_FIREBALL    167
#define CRYSTAL_SFX_GS_INTRO_POKEMON_APPEARS       168
#define CRYSTAL_SFX_FLASH                          169
#define CRYSTAL_SFX_GAME_FREAK_LOGO_GS             170
#define CRYSTAL_SFX_NOT_VERY_EFFECTIVE             171
#define CRYSTAL_SFX_DAMAGE                         172
#define CRYSTAL_SFX_SUPER_EFFECTIVE                173
#define CRYSTAL_SFX_BALL_BOUNCE                    174
#define CRYSTAL_SFX_MOONLIGHT                      175
#define CRYSTAL_SFX_ENCORE                         176
#define CRYSTAL_SFX_BEAT_UP                        177
#define CRYSTAL_SFX_BATON_PASS                     178
#define CRYSTAL_SFX_BALL_WOBBLE                    179
#define CRYSTAL_SFX_SWEET_SCENT                    180
#define CRYSTAL_SFX_SWEET_SCENT_2                  181
#define CRYSTAL_SFX_HIT_END_OF_EXP_BAR             182
#define CRYSTAL_SFX_GIVE_TRADEMON                  183
#define CRYSTAL_SFX_GET_TRADEMON                   184
#define CRYSTAL_SFX_TRAIN_ARRIVED                  185
#define CRYSTAL_SFX_STOP_SLOT                      186
#define CRYSTAL_SFX_2_BOOPS                        187
#define CRYSTAL_SFX_GLASS_TING                     188
#define CRYSTAL_SFX_GLASS_TING_2                   189
#define CRYSTAL_SFX_INTRO_UNOWN_1                  190
#define CRYSTAL_SFX_INTRO_UNOWN_2                  191
#define CRYSTAL_SFX_INTRO_UNOWN_3                  192
#define CRYSTAL_SFX_DITTO_POP_UP                   193
#define CRYSTAL_SFX_DITTO_TRANSFORM                194
#define CRYSTAL_SFX_INTRO_SUICUNE_1                195
#define CRYSTAL_SFX_INTRO_PICHU                    196
#define CRYSTAL_SFX_INTRO_SUICUNE_2                197
#define CRYSTAL_SFX_INTRO_SUICUNE_3                198
#define CRYSTAL_SFX_DITTO_BOUNCE                   199
#define CRYSTAL_SFX_INTRO_SUICUNE_4                200
#define CRYSTAL_SFX_GAME_FREAK_PRESENTS            201
#define CRYSTAL_SFX_TINGLE                         202
#define CRYSTAL_SFX_INTRO_WHOOSH                   203
#define CRYSTAL_SFX_TWO_PC_BEEPS                   204
#define CRYSTAL_SFX_4_NOTE_DITTY                   205
#define CRYSTAL_SFX_TWINKLE                        206

#define CRYSTAL_CRY_NIDORAN_M                      0
#define CRYSTAL_CRY_NIDORAN_F                      1
#define CRYSTAL_CRY_SLOWPOKE                       2
#define CRYSTAL_CRY_KANGASKHAN                     3
#define CRYSTAL_CRY_CHARMANDER                     4
#define CRYSTAL_CRY_GRIMER                         5
#define CRYSTAL_CRY_VOLTORB                        6
#define CRYSTAL_CRY_MUK                            7
#define CRYSTAL_CRY_ODDISH                         8
#define CRYSTAL_CRY_RAICHU                         9
#define CRYSTAL_CRY_NIDOQUEEN                      10
#define CRYSTAL_CRY_DIGLETT                        11
#define CRYSTAL_CRY_SEEL                           12
#define CRYSTAL_CRY_DROWZEE                        13
#define CRYSTAL_CRY_PIDGEY                         14
#define CRYSTAL_CRY_BULBASAUR                      15
#define CRYSTAL_CRY_SPEAROW                        16
#define CRYSTAL_CRY_RHYDON                         17
#define CRYSTAL_CRY_GOLEM                          18
#define CRYSTAL_CRY_BLASTOISE                      19
#define CRYSTAL_CRY_PIDGEOTTO                      20
#define CRYSTAL_CRY_WEEDLE                         21
#define CRYSTAL_CRY_CATERPIE                       22
#define CRYSTAL_CRY_EKANS                          23
#define CRYSTAL_CRY_FEAROW                         24
#define CRYSTAL_CRY_CLEFAIRY                       25
#define CRYSTAL_CRY_VENONAT                        26
#define CRYSTAL_CRY_LAPRAS                         27
#define CRYSTAL_CRY_METAPOD                        28
#define CRYSTAL_CRY_SQUIRTLE                       29
#define CRYSTAL_CRY_PARAS                          30
#define CRYSTAL_CRY_GROWLITHE                      31
#define CRYSTAL_CRY_KRABBY                         32
#define CRYSTAL_CRY_PSYDUCK                        33
#define CRYSTAL_CRY_RATTATA                        34
#define CRYSTAL_CRY_VILEPLUME                      35
#define CRYSTAL_CRY_VULPIX                         36
#define CRYSTAL_CRY_WEEPINBELL                     37
#define CRYSTAL_CRY_MARILL                         38
#define CRYSTAL_CRY_SPINARAK                       39
#define CRYSTAL_CRY_TOGEPI                         40
#define CRYSTAL_CRY_GIRAFARIG                      41
#define CRYSTAL_CRY_RAIKOU                         42
#define CRYSTAL_CRY_MAREEP                         43
#define CRYSTAL_CRY_TOGETIC                        44
#define CRYSTAL_CRY_HOOTHOOT                       45
#define CRYSTAL_CRY_SENTRET                        46
#define CRYSTAL_CRY_SLOWKING                       47
#define CRYSTAL_CRY_CYNDAQUIL                      48
#define CRYSTAL_CRY_CHIKORITA                      49
#define CRYSTAL_CRY_TOTODILE                       50
#define CRYSTAL_CRY_GLIGAR                         51
#define CRYSTAL_CRY_CLEFFA                         52
#define CRYSTAL_CRY_SLUGMA                         53
#define CRYSTAL_CRY_LEDYBA                         54
#define CRYSTAL_CRY_ENTEI                          55
#define CRYSTAL_CRY_WOOPER                         56
#define CRYSTAL_CRY_MANTINE                        57
#define CRYSTAL_CRY_TYPHLOSION                     58
#define CRYSTAL_CRY_NATU                           59
#define CRYSTAL_CRY_TEDDIURSA                      60
#define CRYSTAL_CRY_SUNFLORA                       61
#define CRYSTAL_CRY_AMPHAROS                       62
#define CRYSTAL_CRY_MAGCARGO                       63
#define CRYSTAL_CRY_PICHU                          64
#define CRYSTAL_CRY_AIPOM                          65
#define CRYSTAL_CRY_DUNSPARCE                      66
#define CRYSTAL_CRY_DONPHAN                        67

extern const crystal_audio_track_t gCrystalMusic[CRYSTAL_NUM_MUSIC];
extern const crystal_audio_track_t gCrystalSfx[CRYSTAL_NUM_SFX];
extern const crystal_audio_track_t gCrystalCries[CRYSTAL_NUM_CRIES];

#define CRYSTAL_NUM_TRAINER_CLASSES 71

extern const uint8_t gCrystalTrainerEncounterMusic[CRYSTAL_NUM_TRAINER_CLASSES];

#define CRYSTAL_NUM_MON_CRIES 255
typedef struct { uint16_t index, pitch, length; } crystal_mon_cry_t;
extern const crystal_mon_cry_t gCrystalMonCries[CRYSTAL_NUM_MON_CRIES];
