
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "generated")
OUT = os.path.join(ROOT, "stubs", "crystal")

MODULES = [
    "gen2_pokedex", "gen2_evos_moves", "crystal_palettes", "crystal_font",
    "crystal_menus", "crystal_options", "crystal_pack", "crystal_icons",
    "crystal_stats_screen", "crystal_tile_anims", "crystal_emotes",
    "crystal_audio", "crystal_sprites", "johto_trainers", "crystal_mon_pics",
    "crystal_trainer_pics", "crystal_battle_gfx",
]

BANNER = """/* %s, MIRROR of generated/%s, committed on purpose.
 *
 * Generated by tools/gen_crystal_stubs.py. DO NOT EDIT.
 *
 * The real header is ROM-derived and gitignored. This mirror carries only its
 * INTERFACE, declarations, typedefs and size constants, no asset bytes, so
 * that a RED_ONLY build (no Crystal ROM) still compiles the shared engine
 * files that include it. See tools/gen_crystal_stubs.py.
 */
"""

def strip_comments(text):
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)

def extern_decls(text):
    out = []
    for m in re.finditer(r"^[ \t]*extern[ \t]+([^;]+);", strip_comments(text), re.M):
        out.append(" ".join(m.group(1).split()))
    return out

def prototypes(text):
    out = []
    for m in re.finditer(r"^[ \t]*((?!extern)[A-Za-z_][\w \t*]*\w[ \t]*\([^;{]*\))[ \t]*;",
                         strip_comments(text), re.M):
        out.append(" ".join(m.group(1).split()))
    return out

def c_array_sizes(path):
    sizes = {}
    if not os.path.exists(path):
        return sizes
    text = strip_comments(open(path, encoding="utf-8", errors="replace").read())
    for m in re.finditer(r"\b(\w+)\s*\[\s*\]\s*=\s*\{(.*?)\};", text, re.S):
        sizes[m.group(1)] = len(re.findall(r"0[xX][0-9a-fA-F]+|\b\d+\b", m.group(2)))
    return sizes

def definition_for(decl, sizes):
    if re.search(r"\[\s*\]", decl):
        name = re.search(r"\b(\w+)\s*\[\s*\]", decl)
        n = sizes.get(name.group(1)) if name else None
        if not n:
            return None
        decl = re.sub(r"\[\s*\]", "[%d]" % n, decl, count=1)
    return "%s = {0};" % decl

def build():
    headers, defs, protos, skipped = {}, [], [], []
    for mod in MODULES:
        path = os.path.join(GEN, mod + ".h")
        if not os.path.exists(path):
            raise SystemExit(
                "missing %s -- run the Crystal extractors first; this script\n"
                "mirrors their headers and cannot invent them." % path)
        text = open(path, encoding="utf-8", errors="replace").read()
        headers[mod] = text
        sizes = c_array_sizes(os.path.join(GEN, mod + ".c"))
        for d in extern_decls(text):
            got = definition_for(d, sizes)
            (defs if got else skipped).append(got or d)
        for p in prototypes(text):
            protos.append(p)

    lines = [
        "/* crystal_stubs.c -- the Crystal data, absent.",
        " *",
        " * Generated by tools/gen_crystal_stubs.py. DO NOT EDIT.",
        " *",
        " * Compiled INSTEAD OF the 17 generated/crystal_*.c files when",
        " * RED_ONLY=ON, so a build with no Crystal ROM still links. Every",
        " * symbol here is zero. The engine's Crystal branches compile and are",
        " * simply never reached in a Red-only game -- the player cannot stand",
        " * on a Johto map -- so an empty table is never read, not read-as-empty.",
        " *",
        " * If a Crystal feature ever runs in a Red-only build, it will see",
        " * zeros rather than crash. That is deliberate: a blank tile is a",
        " * better failure than a wild pointer.",
        " */",
    ]
    for mod in MODULES:
        lines.append('#include "%s.h"' % mod)
    lines.append("")
    lines.append("/* %d data symbols, zeroed. */" % len(defs))
    lines.extend(defs)
    lines.append("")
    if protos:
        lines.append("/* %d entry points, answering 'nothing found'. */" % len(protos))
        for p in protos:
            lines.append("%s { return 0; }" % p)
        lines.append("")

    files = {"crystal_stubs.c": "\n".join(lines)}
    for mod, text in headers.items():
        name = mod + ".h"
        files[name] = BANNER % (name, name) + text
    return files, skipped

def main():
    check = "--check" in sys.argv
    files, skipped = build()
    if skipped:
        print("WARNING: %d declaration(s) have an incomplete [] size and were "
              "left out; RED_ONLY will fail to link until they are sized:"
              % len(skipped))
        for s in skipped:
            print("   ", s)

    os.makedirs(OUT, exist_ok=True)
    stale = []
    for name, body in files.items():
        path = os.path.join(OUT, name)
        old = None
        if os.path.exists(path):
            old = open(path, encoding="utf-8", errors="replace").read()
        if old != body:
            stale.append(name)
            if not check:
                with open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(body)

    if check:
        if stale:
            print("STALE stubs (regenerate with tools/gen_crystal_stubs.py): "
                  + ", ".join(sorted(stale)))
            return 1
        print("stubs/crystal is up to date (%d files)" % len(files))
        return 0

    print("wrote %d file(s) to stubs/crystal: 1 stub .c + %d mirrored header(s)"
          % (len(files), len(files) - 1))
    if stale:
        print("  changed: " + ", ".join(sorted(stale)))
    return 0

if __name__ == "__main__":
    sys.exit(main())
