
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import crystal_script as CS
from crystal_rom import Rom

OUT = os.path.join(ROOT, "generated")

TOKEN_FIX = {"<LF>": "\n", "<NEXT>": "\n", "<LINE>": "\n", "<PKMN>": "#MON"}

STRINGS = [
    ("StatusType",  "LoadPinkPage.Status_Type"),
    ("Ok",          "LoadPinkPage.OK_str"),
    ("ExpPoints",   "LoadPinkPage.ExpPointStr"),
    ("LevelUp",     "LoadPinkPage.LevelUpStr"),
    ("To",          "LoadPinkPage.ToStr"),
    ("Pkrs",        "LoadPinkPage.PkrsStr"),
    ("Item",        "LoadGreenPage.Item"),
    ("ThreeDashes", "LoadGreenPage.ThreeDashes"),
    ("Move",        "LoadGreenPage.Move"),

    ("IDNo",        "IDNoString"),
    ("OT",          "OTString"),
]

def text(rom, bank, addr):
    raw = CS.read_text(rom, bank, addr)
    if raw is None:
        return ""
    cm = CS.charmap()
    rev = {}
    for b, t in cm.items():
        rev.setdefault(t, b)
    sub = []
    for b in raw:
        fix = TOKEN_FIX.get(cm.get(b))
        if fix is None:
            sub.append(b)
        elif fix == "\n":
            sub.append(b)
        else:
            sub.extend(rev[ch] for ch in fix if ch in rev)
    s, missing = CS.to_dsl(sub)
    for t in sorted(missing):
        print(f"  !! {addr:#06x}: no port equivalent for {t}")
    return s.replace("\\n", "\n")

NUM_STAT_PAGES = 3

def read_pals(rom):
    b, a = rom.sym["StatsScreenPals"]
    return [rom.u16(b, a + p * 2) for p in range(NUM_STAT_PAGES)]

def tiles_2bpp(rom, bank, addr, n):
    return [bytes(rom.u8(bank, addr + t * 16 + k) for k in range(16))
            for t in range(n)]

def tiles_1bpp(rom, bank, addr, n):
    out = []
    for t in range(n):
        raw = [rom.u8(bank, addr + t * 8 + k) for k in range(8)]
        out.append(bytes(b for r in raw for b in (r, r)))
    return out

LOAD_FONT = [
    (0x31, "StatsScreenPageTilesGFX", 17, 2),
    (0x55, "ExpBarGFX",                8, 2),
    (0x6C, "EnemyHPBarBorderGFX",      4, 1),
    (0x78, "HPExpBarBorderGFX",        1, 1),
    (0x76, "HPExpBarBorderGFX",        2, 1),
]
LOAD_FONT_SKIP = {(0x76, "HPExpBarBorderGFX"): 3}

def read_load_font(rom):
    out = []
    for dest, sym, n, depth in LOAD_FONT:
        b, a = rom.sym[sym]
        a += LOAD_FONT_SKIP.get((dest, sym), 0) * (8 if depth == 1 else 16)
        t = tiles_1bpp(rom, b, a, n) if depth == 1 else tiles_2bpp(rom, b, a, n)
        out.append((dest, sym, t))
    return out

WHITE, BLACK = 0x7FFF, 0x0000

def expand(c1, c2):
    return [WHITE, c1, c2, BLACK]

def read_cgb_pals(rom):
    hb, ha = rom.sym["HPBarPals"]
    hp = [expand(rom.u16(hb, ha + i * 4), rom.u16(hb, ha + i * 4 + 2))
          for i in range(3)]
    eb, ea = rom.sym["ExpBarPalette"]
    exp = expand(rom.u16(eb, ea), rom.u16(eb, ea + 2))
    pb, pa = rom.sym["StatsScreenPagePals"]
    page = [[rom.u16(pb, pa + p * 8 + c * 2) for c in range(4)]
            for p in range(NUM_STAT_PAGES)]
    return hp, exp, page

def cstr(s):
    out = ""
    for ch in s:
        if ord(ch) > 0x7E and ch != "\n":
            continue
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif ch == "\n":
            out += "\\n"
        else:
            out += ch
    return '"' + out + '"'

def emit_pal_block(f, name, rows, labels):
    f.write(f"const uint16_t {name}[{len(rows)}][4] = {{\n")
    for i, p in enumerate(rows):
        f.write(f"    /* {labels[i]:6s} */ {{ "
                + ", ".join(f"0x{v:04X}" for v in p) + " },\n")
    f.write("};\n\n")

def emit(strings, pals, cgb, gfx):
    os.makedirs(OUT, exist_ok=True)
    h = os.path.join(OUT, "crystal_stats_screen.h")
    c = os.path.join(OUT, "crystal_stats_screen.c")
    with open(h, "w", newline="\n", encoding="utf-8") as f:
        f.write(
            "/* crystal_stats_screen.h -- GENERATED by\n"
            " * tools/romimport/extract_crystal_stats_screen.py.  DO NOT EDIT.\n"
            " *\n"
            " * Crystal's summary-screen text and palettes, read from the ROM.\n"
            " * The per-page LAYOUT is not here: LoadPinkPage/GreenPage/BluePage\n"
            " * place with inline hlcoords, so there is no tilemap to extract.\n"
            " * ROM-derived: never commit. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            f"#define CRYSTAL_STATS_PALS {len(pals)}   /* pages */\n"
            "/* Three pages (PINK/GREEN/BLUE) each carry their own palettes --\n"
            " * that is why the screen changes colour as you page through. */\n"
            "extern const uint16_t gCrystalStatsPageColor[CRYSTAL_STATS_PALS];\n\n")
        for name, _sym, _raw in strings:
            f.write(f"extern const char *const gCrystalStats{name};\n")
        f.write(
            "\n/* RAW GB CHARACTER CODES, $50-terminated -- the same strings\n"
            " * before any ASCII transcription.  Some of these CANNOT survive\n"
            " * the ASCII round trip: IDNoString is db \"<ID>\\u2116.@\", where\n"
            " * <ID> is a two-tile ligature and \\u2116 is a numero sign, and\n"
            " * to_dsl turns them into punctuation soup.  The Gen 2 font loads\n"
            " * all 128 tiles, so the glyphs are in VRAM -- feed these through\n"
            " * Font_CharToTile instead of retyping the strings as \"ID No.\". */\n")
        for name, _sym, _raw in strings:
            f.write(f"extern const uint8_t gCrystalStats{name}Raw[];\n")
        f.write(
            "\n/* _CGB_StatsScreenHPPals' BG set (cgb_layouts.asm:198):\n"
            " *   0 HP bar (by HP band)   1 mon   2 exp bar   3-5 page squares\n"
            " * LoadStatsScreenPals then overwrites COLOUR 0 of palettes 0 and\n"
            " * 2 with the page tint -- which only makes sense once THIS set is\n"
            " * loaded.  Applying the tint over an inherited palette repaints\n"
            " * the whole screen. */\n"
            "extern const uint16_t gCrystalStatsHPBarPals[3][4];\n"
            "extern const uint16_t gCrystalStatsExpBarPal[1][4];\n"
            "extern const uint16_t "
            "gCrystalStatsPagePals[CRYSTAL_STATS_PALS][4];\n")
        f.write(
            "\n/* StatsScreen_LoadFont (load_font.asm:121).  The stats screen\n"
            " * cannot be drawn without these: every tile id the pages write\n"
            " * ($31 divider, $36/$3A page squares, $3F shiny, $40/$41 bar end\n"
            " * caps, $55.. exp bar) comes from here.  StatsScreen_LoadGFX does\n"
            " * NOT load them -- the wrapper calls StatsScreen_LoadFont once,\n"
            " * separately, which is exactly why it is easy to miss. */\n"
            "typedef struct {\n"
            "    uint8_t dest_tile;      /* vTiles2 tile index */\n"
            "    uint8_t count;\n"
            "    const uint8_t (*tiles)[16];   /* already 2bpp */\n"
            "} crystal_stats_gfx_t;\n"
            f"#define CRYSTAL_STATS_GFX_SETS {len(LOAD_FONT)}\n"
            "extern const crystal_stats_gfx_t "
            "gCrystalStatsGFX[CRYSTAL_STATS_GFX_SETS];\n")
    with open(c, "w", newline="\n", encoding="utf-8") as f:
        f.write('/* crystal_stats_screen.c -- GENERATED, see the header. */\n'
                '#include "crystal_stats_screen.h"\n\n')
        f.write("const uint16_t gCrystalStatsPageColor[CRYSTAL_STATS_PALS] = {\n")
        lbl = ["PINK", "GREEN", "BLUE"]
        for i, v in enumerate(pals):
            f.write(f"    /* {lbl[i]:5s} */ 0x{v:04X},"
                    f"  /* {v & 31:2d},{(v >> 5) & 31:2d},{(v >> 10) & 31:2d} */\n")
        f.write("};\n\n")
        for name, val, _raw in strings:
            f.write(f"const char *const gCrystalStats{name} = {cstr(val)};\n")
        f.write("\n")
        for name, _val, raw in strings:
            body = ", ".join(f"0x{b:02X}" for b in raw)
            f.write(f"const uint8_t gCrystalStats{name}Raw[] = {{ {body} }};\n")
        hp, expp, page = cgb
        f.write("\n")
        emit_pal_block(f, "gCrystalStatsHPBarPals", hp,
                       ["GREEN", "YELLOW", "RED"])
        emit_pal_block(f, "gCrystalStatsExpBarPal", [expp], ["EXP"])
        emit_pal_block(f, "gCrystalStatsPagePals", page,
                       ["PINK", "GREEN", "BLUE"])
        for dest, sym, tiles in gfx:

            f.write(f"static const uint8_t k{sym}_{dest:02X}"
                    f"[{len(tiles)}][16] = {{\n")
            for t in tiles:
                f.write("    { " + ", ".join(f"0x{b:02X}" for b in t) + " },\n")
            f.write("};\n")
        f.write("\nconst crystal_stats_gfx_t "
                "gCrystalStatsGFX[CRYSTAL_STATS_GFX_SETS] = {\n")
        for dest, sym, tiles in gfx:
            f.write(f"    {{ 0x{dest:02X}, {len(tiles)}, k{sym}_{dest:02X} }},"
                    f"  /* {sym} */\n")
        f.write("};\n")
    return h, c

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.sym"))
    args = ap.parse_args()
    rom = Rom(args.rom, args.sym)

    out = []
    for name, sym in STRINGS:
        if sym not in rom.sym:
            print(f"  !! symbol not found: {sym}")
            out.append((name, "", [0x50]))
            continue
        b, a = rom.sym[sym]
        raw = CS.read_text(rom, b, a) or []
        raw = list(raw) + [0x50]
        out.append((name, text(rom, b, a), raw))

    pals = read_pals(rom)
    cgb = read_cgb_pals(rom)
    gfx = read_load_font(rom)
    h, c = emit(out, pals, cgb, gfx)
    print(f"  HP bar pals {len(cgb[0])}, exp bar 1, page pals {len(cgb[2])}")
    for dest, sym, tiles in gfx:
        print(f"  gfx ${dest:02X} {sym:26s} {len(tiles):2d} tiles")
    print(f"{len(pals)} palettes, {len(out)} strings")
    for name, val, raw in out:
        print(f"  {name:12s} {val!r:16s} raw "
              + " ".join(f"{b:02X}" for b in raw))
    print(" ", h)
    print(" ", c)
    return 0

if __name__ == "__main__":
    sys.exit(main())
