
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

from crystal_rom import Rom

OUT = os.path.join(ROOT, "generated")
SRC = os.path.join(ROOT, "pokecrystal-master")

ICON_TILES = 8
NUM_SPECIES = 251

def icon_names():
    path = os.path.join(SRC, "constants", "icon_constants.asm")
    out, n = [], 0
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.split(";")[0]
        m = re.match(r"\s*const_def\s*(-?\d+)?", line)
        if m:
            n = int(m.group(1)) if m.group(1) else 0
            continue
        m = re.match(r"\s*const\s+ICON_(\w+)", line)
        if m:
            out.append(m.group(1))
            n += 1
    return out

def extract(rom):
    mb, ma = rom.sym["MonMenuIcons"]
    species_icon = [rom.u8(mb, ma + i) for i in range(NUM_SPECIES)]

    pb, pa = rom.sym["IconPointers"]
    end = rom.next_symbol_addr(pb, pa)
    count = (end - pa) // 2 if end else 0
    ptrs = [rom.u16(pb, pa + i * 2) for i in range(count)]

    icons = []
    for p in ptrs:
        icons.append([bytes(rom.u8(pb, p + t * 16 + k) for k in range(16))
                      for t in range(ICON_TILES)])
    return species_icon, icons

def read_party_bg_pals(rom):
    pb, pa = rom.sym["PalPacket_PartyMenu"]
    qb, qa = rom.sym["PredefPals"]
    ids = [rom.u8(pb, pa + 1 + i * 2) for i in range(4)]
    return ids, [[rom.u16(qb, qa + i * 8 + c * 2) for c in range(4)]
                 for i in ids]

def read_obpals(rom):
    b, a = rom.sym["PartyMenuOBPals"]
    end = rom.next_symbol_addr(b, a)
    n = (end - a) // 8 if end else 8
    if n > 8:
        n = 8
    return [[rom.u16(b, a + p * 8 + c * 2) for c in range(4)] for p in range(n)]

def verify(icons, names):
    d = os.path.join(SRC, "gfx", "icons")
    ok = bad = missing = 0
    for i, tiles in enumerate(icons):
        nm = names[i].lower() if i < len(names) else None
        if not nm:
            continue
        path = os.path.join(d, nm + ".2bpp")
        if not os.path.isfile(path):
            missing += 1
            continue
        raw = open(path, "rb").read()
        got = b"".join(tiles)
        if got[:len(raw)] == raw:
            ok += 1
        else:
            bad += 1
            if bad <= 5:
                print(f"  !! {nm}: differs")
    print(f"\nicons verify: {ok} identical, {bad} differ, {missing} with no file")
    return bad == 0

def emit(species_icon, icons, names, obpals, bgpals):
    os.makedirs(OUT, exist_ok=True)
    h = os.path.join(OUT, "crystal_icons.h")
    c = os.path.join(OUT, "crystal_icons.c")

    with open(h, "w", newline="\n", encoding="utf-8") as f:
        f.write(
            "/* crystal_icons.h -- GENERATED by "
            "tools/romimport/extract_crystal_icons.py.  DO NOT EDIT.\n"
            " *\n"
            " * Party-menu mon icons, read from the user's own ROM.  This port\n"
            " * has no Gen 2 icons at all (gMonPartyIconType is [152]), so this\n"
            " * is the party screen's missing asset, not a restyling.\n"
            " * ROM-derived: never commit. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            f"#define CRYSTAL_ICON_TILES {ICON_TILES}   /* 2 frames x 4 */\n"
            f"#define CRYSTAL_NUM_ICONS  {len(icons)}\n"
            f"#define CRYSTAL_ICON_SPECIES {NUM_SPECIES}\n\n"
            "/* INDEX WITH dex - 1.  MonMenuIcons runs in dex order from\n"
            " * BULBASAUR, so entry 0 is dex 1 -- the same off-by-one as the\n"
            " * item descriptions.  Value is an index into gCrystalIcon. */\n"
            "extern const uint8_t gCrystalSpeciesIcon[CRYSTAL_ICON_SPECIES];\n"
            "/* [icon][tile][16].  Tiles 0-3 are frame 0, tiles 4-7 frame 1 --\n"
            " * the icons ANIMATE; the party menu runs them as OAM sprites\n"
            " * through PlaySpriteAnimations, not as BG tiles. */\n"
            "extern const uint8_t "
            "gCrystalIcon[CRYSTAL_NUM_ICONS][CRYSTAL_ICON_TILES][16];\n"
            f"#define CRYSTAL_ICON_OBPALS {len(obpals)}\n"
            "/* PartyMenuOBPals -- the OBJ palettes icons are drawn with. */\n"
            "extern const uint16_t gCrystalIconOBPals[CRYSTAL_ICON_OBPALS][4];\n"
            "/* The party menu's four BG palettes, in slot order:\n"
            " *   0 PARTY_ICON   1 HP_GREEN   2 HP_YELLOW   3 HP_RED\n"
            " * CGB_ApplyPartyMenuHPPals gives each mon's HP-bar box palette\n"
            " * (its HP band + 1), so 1/2/3.  They differ ONLY in colour 2 --\n"
            " * which is the bar's fill -- so a bar left on palette 0 is grey. */\n"
            "extern const uint16_t gCrystalPartyMenuBGPals[4][4];\n")

    with open(c, "w", newline="\n", encoding="utf-8") as f:
        f.write('/* crystal_icons.c -- GENERATED, see the header. */\n'
                '#include "crystal_icons.h"\n\n')
        f.write("const uint8_t gCrystalSpeciesIcon[CRYSTAL_ICON_SPECIES] = {\n")
        for i in range(0, NUM_SPECIES, 16):
            row = species_icon[i:i + 16]
            f.write(f"    /* dex {i + 1:3d} */ "
                    + ", ".join(str(v) for v in row) + ",\n")
        f.write("};\n\n")
        f.write("const uint8_t "
                "gCrystalIcon[CRYSTAL_NUM_ICONS][CRYSTAL_ICON_TILES][16] = {\n")
        for i, tiles in enumerate(icons):
            nm = names[i] if i < len(names) else f"ICON_{i}"
            f.write(f"    /* {i:2d} {nm} */ {{\n")
            for t in tiles:
                f.write("        { " + ", ".join(f"0x{b:02X}" for b in t)
                        + " },\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("const uint16_t gCrystalIconOBPals[CRYSTAL_ICON_OBPALS][4] = {\n")
        for p in obpals:
            f.write("    { " + ", ".join(f"0x{v:04X}" for v in p) + " },\n")
        f.write("};\n\n")
        f.write("const uint16_t gCrystalPartyMenuBGPals[4][4] = {\n")
        lbl = ["PARTY_ICON", "HP_GREEN", "HP_YELLOW", "HP_RED"]
        for i, p in enumerate(bgpals):
            rgbs = "  ".join(f"{v & 31:2d},{(v >> 5) & 31:2d},{(v >> 10) & 31:2d}"
                             for v in p)
            f.write(f"    /* {lbl[i]:10s} */ {{ "
                    + ", ".join(f"0x{v:04X}" for v in p)
                    + f" }},  /* {rgbs} */\n")
        f.write("};\n")
    return h, c

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(SRC, "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(SRC, "pokecrystal.sym"))
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()

    rom = Rom(args.rom, args.sym)
    species_icon, icons = extract(rom)
    names = icon_names()
    obpals = read_obpals(rom)
    pal_ids, bgpals = read_party_bg_pals(rom)
    h, c = emit(species_icon, icons, names, obpals, bgpals)
    print(f"{len(icons)} icons x {ICON_TILES} tiles, "
          f"{NUM_SPECIES} species mapped, {len(obpals)} OBJ palettes")
    print(f"  icon constants parsed: {len(names)}")
    print(" ", h)
    print(" ", c)
    if args.verify and not verify(icons, names):
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
