
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import crystal_maps as M
from crystal_rom import Rom

PC = os.path.join(ROOT, "pokecrystal-master")
OUT = os.path.join(ROOT, "generated")

BG_SETS = [("MORN", 8), ("DAY", 8), ("NITE", 8), ("DARK", 8), ("INDOOR", 8),
           ("WATER", 2)]

PAL_NAMES = ["GRAY", "RED", "GREEN", "WATER", "YELLOW", "BROWN", "ROOF", "TEXT"]

def read_palettes(rom, bank, addr, count):
    return [[rom.u16(bank, addr + p * 8 + c * 2) for c in range(4)]
            for p in range(count)]

def read_palmap(rom, bank, addr, ntiles):
    pals, banks = [], []
    for i in range((ntiles + 1) // 2):
        byte = rom.u8(bank, addr + i)
        for nib in (byte & 0x0F, byte >> 4):
            pals.append(nib & 0x07)
            banks.append(1 if nib & 0x08 else 0)
    return pals[:ntiles], banks[:ntiles]

def tileset_names(rom):
    consts = M.const_table(os.path.join(PC, "constants",
                                        "tileset_constants.asm"))
    bank, addr = rom.sym["Tilesets"]
    out = {}
    for name, tsid in consts.items():
        if not name.startswith("TILESET_") or name.endswith("_LENGTH"):
            continue
        if not isinstance(tsid, int):
            continue
        a = addr + tsid * 15
        out[name] = (tsid, bank, rom.u16(bank, a + 13))
    return out

def emit(rom):
    bgb, bga = rom.sym["TilesetBGPalette"]
    total = sum(n for _s, n in BG_SETS)
    bg = read_palettes(rom, bgb, bga, total)

    ob, oa = rom.sym["MapObjectPals"]
    obj = read_palettes(rom, ob, oa, 4 * 8)

    rb, ra = rom.sym["RoofPals"]
    end = rom.next_symbol_addr(rb, ra)

    ngroups = (end - ra) // 8 if end else 0
    roofs = [[rom.u16(rb, ra + g * 8 + i * 2) for i in range(4)]
             for g in range(ngroups)]

    tb, ta = rom.sym["Palette_TextBG7"]
    text_bg7 = read_palettes(rom, tb, ta, 1)[0]

    tilesets = tileset_names(rom)

    eb, ea = rom.sym["EnvironmentColorsPointers"]

    eend = rom.next_symbol_addr(eb, ea)
    nenv = ((eend - ea) // 2) - 1 if eend else 0
    envs = []
    for e in range(nenv + 1):
        ptr = rom.u16(eb, ea + e * 2)
        envs.append([[rom.u8(eb, ptr + t * 8 + s) for s in range(8)]
                     for t in range(4)])

    os.makedirs(OUT, exist_ok=True)
    hpath = os.path.join(OUT, "crystal_palettes.h")
    cpath = os.path.join(OUT, "crystal_palettes.c")

    with open(hpath, "w", newline="\n") as f:
        f.write("/* crystal_palettes.h -- GENERATED by "
                "tools/romimport/extract_crystal_palettes.py.  DO NOT EDIT.\n"
                " *\n"
                " * Crystal's overworld colour data, read from pokecrystal.gbc.\n"
                " * ROM-derived: never commit this file.\n */\n"
                "#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define CRYSTAL_NUM_BG_PALETTES {total}\n")
        off = 0
        for setname, n in BG_SETS:
            f.write(f"#define CRYSTAL_PAL_{setname} {off}  /* {n} palettes */\n")
            off += n
        f.write("\n")
        for i, nm in enumerate(PAL_NAMES):
            f.write(f"#define CRYSTAL_PAL_BG_{nm} {i}\n")
        f.write(f"\n#define CRYSTAL_NUM_ROOF_GROUPS {ngroups}\n")
        f.write(f"#define CRYSTAL_NUM_ENVIRONMENTS {nenv + 1}\n")
        f.write("#define CRYSTAL_TOD_MORN 0\n#define CRYSTAL_TOD_DAY  1\n"
                "#define CRYSTAL_TOD_NITE 2\n#define CRYSTAL_TOD_DARK 3\n\n")
        f.write("/* [palette][colour], BGR555 exactly as the hardware reads it. */\n"
                "extern const uint16_t gCrystalBGPalettes"
                "[CRYSTAL_NUM_BG_PALETTES][4];\n"
                "/* [map group][0..1 = morn/day pair, 2..3 = nite pair] */\n"
                "extern const uint16_t gCrystalRoofPals"
                "[CRYSTAL_NUM_ROOF_GROUPS][4];\n"
                "/* Overworld SPRITE palettes: [time of day][0-7][colour].\n"
                " * An object_event's palette nibble is a PAL_NPC_* constant\n"
                " * (8-15), so the index is that value & 7; 0 means the sprite's\n"
                " * own default rather than palette 0. */\n"
                "extern const uint16_t gCrystalObjectPals[4][8][4];\n"
                "/* [environment][time of day][BG slot 0-7] -> index into\n"
                " * gCrystalBGPalettes.  This is what a tileset palette map's\n"
                " * 0-7 actually resolves through. */\n"
                "extern const uint8_t gCrystalEnvColors"
                "[CRYSTAL_NUM_ENVIRONMENTS][4][8];\n"
                "/* Palette_TextBG7 (gfx/font/bg_text.pal) -- the overworld\n"
                " * TEXT palette, which overwrites BG slot 7 right after the\n"
                " * map palettes are loaded (LoadOW_BGPal7).  Use THIS for the\n"
                " * textbox and menu frame, not gCrystalBGPalettes' `text`\n"
                " * entry: that one is a cream placeholder LoadMapPals writes\n"
                " * and nothing ever renders with.  Time-of-day independent. */\n"
                "extern const uint16_t gCrystalTextBGPal[4];\n")

    with open(cpath, "w", newline="\n") as f:
        f.write("/* crystal_palettes.c -- GENERATED, see the header. */\n"
                '#include "crystal_palettes.h"\n\n')
        f.write("const uint16_t gCrystalBGPalettes"
                "[CRYSTAL_NUM_BG_PALETTES][4] = {\n")
        idx = 0
        for setname, n in BG_SETS:
            f.write(f"    /* ---- {setname} ---- */\n")
            for p in range(n):
                cols = bg[idx]
                nm = PAL_NAMES[p] if p < len(PAL_NAMES) else f"P{p}"
                rgb = "  ".join(
                    f"{v & 31:2d},{(v >> 5) & 31:2d},{(v >> 10) & 31:2d}"
                    for v in cols)
                f.write(f"    /* {idx:2d} {setname}_{nm:6s} */ {{ "
                        + ", ".join(f"0x{v:04X}" for v in cols)
                        + f" }},  /* {rgb} */\n")
                idx += 1
        f.write("};\n\n")
        f.write("const uint16_t gCrystalRoofPals"
                "[CRYSTAL_NUM_ROOF_GROUPS][4] = {\n")
        for g, cols in enumerate(roofs):
            f.write(f"    /* group {g:2d} */ {{ "
                    + ", ".join(f"0x{v:04X}" for v in cols) + " },\n")
        f.write("};\n\n")
        f.write("const uint16_t gCrystalObjectPals[4][8][4] = {\n")
        OBJ_NAMES = ["RED", "BLUE", "GREEN", "BROWN", "PINK", "SILVER",
                     "TREE", "ROCK"]
        for t, tname in enumerate(["morn", "day", "nite", "dark"]):
            f.write(f"    /* ---- {tname} ---- */ {{\n")
            for p in range(8):
                cols = obj[t * 8 + p]
                f.write(f"        /* {OBJ_NAMES[p]:6s} */ {{ "
                        + ", ".join(f"0x{v:04X}" for v in cols) + " },\n")
            f.write("    },\n")
        f.write("};\n\n")
        rgb7 = "  ".join(f"{v & 31:2d},{(v >> 5) & 31:2d},{(v >> 10) & 31:2d}"
                         for v in text_bg7)
        f.write("const uint16_t gCrystalTextBGPal[4] = { "
                + ", ".join(f"0x{v:04X}" for v in text_bg7)
                + f" }};  /* {rgb7} */\n\n")
        f.write("const uint8_t gCrystalEnvColors"
                "[CRYSTAL_NUM_ENVIRONMENTS][4][8] = {\n")
        tod = ["morn", "day", "nite", "dark"]
        for e, rowset in enumerate(envs):
            f.write(f"    /* environment {e} */ {{\n")
            for t, row in enumerate(rowset):
                f.write(f"        /* {tod[t]:4s} */ {{ "
                        + ", ".join(f"0x{v:02X}" for v in row) + " },\n")
            f.write("    },\n")
        f.write("};\n")

    print(f"{total} BG palettes, {ngroups} roof groups, "
          f"{len(envs)} environments, {len(tilesets)} tilesets")
    print(f"  {hpath}")
    print(f"  {cpath}")
    return {"bg": bg, "roofs": roofs, "tilesets": tilesets, "envs": envs,
            "obj": obj}

def verify(rom, res):
    ok = fail = 0

    def rgb_lines(path):
        out = []
        for line in open(path, encoding="utf-8"):
            m = re.match(r"\s*RGB\s+(.*?)(?:;.*)?$", line)
            if m:
                out.append([int(n) for n in re.findall(r"\d+", m.group(1))])
        return out

    print("\n--- TilesetBGPalette vs gfx/tilesets/bg_tiles.pal ---")
    want = rgb_lines(os.path.join(PC, "gfx", "tilesets", "bg_tiles.pal"))
    if len(want) != len(res["bg"]):
        print(f"  !! {len(want)} palettes in the .pal, {len(res['bg'])} read")
        fail += 1
    for i, nums in enumerate(want[:len(res["bg"])]):
        for c in range(4):
            v = res["bg"][i][c]
            got = (v & 31, (v >> 5) & 31, (v >> 10) & 31)
            if got == tuple(nums[c * 3:c * 3 + 3]):
                ok += 1
            else:
                fail += 1
                if fail <= 5:
                    print(f"  !! palette {i} colour {c}: rom {got} "
                          f"asm {tuple(nums[c*3:c*3+3])}")

    print("--- MapObjectPals vs gfx/overworld/npc_sprites.pal ---")
    want = rgb_lines(os.path.join(PC, "gfx", "overworld", "npc_sprites.pal"))
    if len(want) != len(res["obj"]):
        print(f"  !! {len(want)} palettes in the .pal, {len(res['obj'])} read")
        fail += 1
    for i, nums in enumerate(want[:len(res["obj"])]):
        for c in range(4):
            v = res["obj"][i][c]
            got = (v & 31, (v >> 5) & 31, (v >> 10) & 31)
            if got == tuple(nums[c * 3:c * 3 + 3]):
                ok += 1
            else:
                fail += 1
                if fail <= 5:
                    print(f"  !! sprite palette {i} colour {c}: rom {got} "
                          f"asm {tuple(nums[c*3:c*3+3])}")

    print("--- RoofPals vs gfx/tilesets/roofs.pal ---")
    want = rgb_lines(os.path.join(PC, "gfx", "tilesets", "roofs.pal"))
    flat = [c for line in want for c in
            [tuple(line[0:3]), tuple(line[3:6])]]
    for g, cols in enumerate(res["roofs"]):
        for i, v in enumerate(cols):
            n = g * 4 + i
            if n >= len(flat):
                break
            got = (v & 31, (v >> 5) & 31, (v >> 10) & 31)
            if got == flat[n]:
                ok += 1
            else:
                fail += 1
                if fail <= 10:
                    print(f"  !! roof group {g} colour {i}: rom {got} "
                          f"asm {flat[n]}")

    print("")
    src = open(os.path.join(PC, "data", "maps", "environment_colors.asm"),
               encoding="utf-8").read()

    tables = {}
    for m in re.finditer(r"^\.(\w+):\s*\n((?:\s*db .*\n)+)", src, re.M):
        rows = []
        for line in m.group(2).splitlines():
            vals = re.findall(r"\$([0-9a-fA-F]{2})", line)
            if vals:
                rows.append([int(v, 16) for v in vals])
        tables["." + m.group(1)] = rows

    order = re.findall(r"^\tdw (\.\w+)", src, re.M)
    for e, label in enumerate(order):
        if e >= len(res["envs"]) or label not in tables:
            continue
        for t in range(4):
            for s in range(8):
                if res["envs"][e][t][s] == tables[label][t][s]:
                    ok += 1
                else:
                    fail += 1
                    if fail <= 10:
                        print(f"  !! env {e} ({label}) tod {t} slot {s}: "
                              f"rom ${res['envs'][e][t][s]:02X} "
                              f"asm ${tables[label][t][s]:02X}")
    print(f"  environments checked: {len(order)}")

    print("--- PalMaps vs gfx/tilesets/*_palette_map.asm ---")
    checked = 0
    for tsname, (tsid, bank, ptr) in sorted(res["tilesets"].items(),
                                            key=lambda kv: kv[1][0]):
        slug = tsname[len("TILESET_"):].lower()
        path = os.path.join(PC, "gfx", "tilesets", f"{slug}_palette_map.asm")
        if not os.path.exists(path):
            continue

        want = []
        pending_rept = 0
        for line in open(path, encoding="utf-8"):
            s = line.split(";")[0].strip()
            m = re.match(r"tilepal\s+\d+\s*,\s*(.*)$", s)
            if m:
                want += [p.strip() for p in m.group(1).split(",") if p.strip()]
                continue
            m = re.match(r"rept\s+(\d+)", s)
            if m:
                pending_rept = int(m.group(1))
                continue
            if pending_rept and re.match(r"db\s+\$ff", s, re.I):
                want += [None] * (pending_rept * 2)
                pending_rept = 0
        pals, _banks = read_palmap(rom, bank, ptr, len(want))
        checked += 1
        for i, nm in enumerate(want):
            if nm is None or nm not in PAL_NAMES:
                continue
            if pals[i] == PAL_NAMES.index(nm):
                ok += 1
            else:
                fail += 1
                if fail <= 10:
                    print(f"  !! {tsname} tile {i}: rom "
                          f"{PAL_NAMES[pals[i]]} asm {nm}")
    print(f"  palette maps checked: {checked}")

    print(f"\nverify: {ok} values match, {fail} differ")
    return fail == 0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(PC, "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(PC, "pokecrystal.sym"))
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()
    rom = Rom(args.rom, args.sym)
    res = emit(rom)
    if args.verify:
        return 0 if verify(rom, res) else 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
