
import argparse
import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import crystal_maps as M
from crystal_rom import Rom

PC = os.path.join(ROOT, "pokecrystal-master")
OUT = os.path.join(ROOT, "generated")

GRASS_SLOTS, WATER_SLOTS = 7, 3
TIMES = ("morn", "day", "nite")
END_MARKER = 0xFF

def read_grass(rom, bank, addr, id_to_name):
    out = []
    while rom.u8(bank, addr) != END_MARKER:
        g, m = rom.u8(bank, addr), rom.u8(bank, addr + 1)
        rates = [rom.u8(bank, addr + 2 + i) for i in range(3)]
        sets = []
        p = addr + 5
        for _t in range(3):
            slots = []
            for _s in range(GRASS_SLOTS):
                slots.append((rom.u8(bank, p), rom.u8(bank, p + 1)))
                p += 2
            sets.append(slots)
        out.append({"group": g, "map": m, "name": id_to_name.get((g, m)),
                    "rates": rates, "sets": sets})
        addr = p
    return out

def read_water(rom, bank, addr, id_to_name):
    out = []
    while rom.u8(bank, addr) != END_MARKER:
        g, m = rom.u8(bank, addr), rom.u8(bank, addr + 1)
        rate = rom.u8(bank, addr + 2)
        p = addr + 3
        slots = []
        for _s in range(WATER_SLOTS):
            slots.append((rom.u8(bank, p), rom.u8(bank, p + 1)))
            p += 2
        out.append({"group": g, "map": m, "name": id_to_name.get((g, m)),
                    "rate": rate, "slots": slots})
        addr = p
    return out

def read_probs(rom, sym, n):
    b, a = rom.sym[sym]

    return [(rom.u8(b, a + i * 2), rom.u8(b, a + i * 2 + 1) // 2)
            for i in range(n)]

def emit(rom):
    table = M.build_map_table(rom)
    id_to_name = table[0]
    grass, water = [], []
    for sym in ("JohtoGrassWildMons", "KantoGrassWildMons"):
        b, a = rom.sym[sym]
        grass += read_grass(rom, b, a, id_to_name)
    for sym in ("JohtoWaterWildMons", "KantoWaterWildMons"):
        b, a = rom.sym[sym]
        water += read_water(rom, b, a, id_to_name)
    gprob = read_probs(rom, "GrassMonProbTable", GRASS_SLOTS)
    wprob = read_probs(rom, "WaterMonProbTable", WATER_SLOTS)

    os.makedirs(OUT, exist_ok=True)
    hpath = os.path.join(OUT, "crystal_wild.h")
    cpath = os.path.join(OUT, "crystal_wild.c")

    with open(hpath, "w", newline="\n") as f:
        f.write("/* crystal_wild.h -- GENERATED by\n"
                " * tools/romimport/extract_crystal_wild.py.  DO NOT EDIT.\n"
                " * ROM-derived: never commit this file. */\n"
                "#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define CRYSTAL_GRASS_SLOTS {GRASS_SLOTS}\n"
                f"#define CRYSTAL_WATER_SLOTS {WATER_SLOTS}\n"
                f"#define CRYSTAL_NUM_GRASS_MAPS {len(grass)}\n"
                f"#define CRYSTAL_NUM_WATER_MAPS {len(water)}\n"
                "#define CRYSTAL_TOD_SETS 3   /* morn, day, nite */\n\n")
        f.write("typedef struct { uint8_t level, species; } crystal_wild_slot_t;\n\n")
        f.write("typedef struct {\n"
                "    const char *map;                 /* NULL if unnamed */\n"
                "    uint8_t     group, number;\n"
                "    uint8_t     rate[CRYSTAL_TOD_SETS];\n"
                "    crystal_wild_slot_t slots[CRYSTAL_TOD_SETS][CRYSTAL_GRASS_SLOTS];\n"
                "} crystal_wild_grass_t;\n\n")
        f.write("typedef struct {\n"
                "    const char *map;\n"
                "    uint8_t     group, number;\n"
                "    uint8_t     rate;\n"
                "    crystal_wild_slot_t slots[CRYSTAL_WATER_SLOTS];\n"
                "} crystal_wild_water_t;\n\n")
        f.write("/* Cumulative percent thresholds -- slot i is chosen when the\n"
                " * roll is below threshold[i].  Gen 2's curve is 30/30/20/10/\n"
                " * 5/4/1, which is NOT the ten-slot Gen 1 curve wild_data.h\n"
                " * models; see this extractor's docstring. */\n"
                "extern const uint8_t gCrystalGrassProb[CRYSTAL_GRASS_SLOTS];\n"
                "extern const uint8_t gCrystalWaterProb[CRYSTAL_WATER_SLOTS];\n"
                "extern const crystal_wild_grass_t "
                "gCrystalWildGrass[CRYSTAL_NUM_GRASS_MAPS];\n"
                "extern const crystal_wild_water_t "
                "gCrystalWildWater[CRYSTAL_NUM_WATER_MAPS];\n")

    with open(cpath, "w", newline="\n") as f:
        f.write("/* crystal_wild.c -- GENERATED, see the header. */\n"
                '#include "crystal_wild.h"\n\n')
        f.write("const uint8_t gCrystalGrassProb[CRYSTAL_GRASS_SLOTS] = { "
                + ", ".join(str(p) for p, _i in gprob) + " };\n")
        f.write("const uint8_t gCrystalWaterProb[CRYSTAL_WATER_SLOTS] = { "
                + ", ".join(str(p) for p, _i in wprob) + " };\n\n")
        f.write("const crystal_wild_grass_t "
                "gCrystalWildGrass[CRYSTAL_NUM_GRASS_MAPS] = {\n")
        for e in grass:
            nm = f'"{e["name"]}"' if e["name"] else "0"
            f.write(f"    {{ {nm}, {e['group']}, {e['map']}, "
                    f"{{ {', '.join(str(r) for r in e['rates'])} }}, {{\n")
            for t, slots in enumerate(e["sets"]):
                f.write(f"        /* {TIMES[t]:4s} */ {{ "
                        + ", ".join(f"{{{l},{s}}}" for l, s in slots) + " },\n")
            f.write("    } },\n")
        f.write("};\n\n")
        f.write("const crystal_wild_water_t "
                "gCrystalWildWater[CRYSTAL_NUM_WATER_MAPS] = {\n")
        for e in water:
            nm = f'"{e["name"]}"' if e["name"] else "0"
            f.write(f"    {{ {nm}, {e['group']}, {e['map']}, {e['rate']}, {{ "
                    + ", ".join(f"{{{l},{s}}}" for l, s in e["slots"])
                    + " } },\n")
        f.write("};\n")

    named = sum(1 for e in grass if e["name"])
    print(f"grass: {len(grass)} maps ({named} named), water: {len(water)} maps")
    print(f"grass prob curve: {[p for p, _ in gprob]}  "
          f"water: {[p for p, _ in wprob]}")
    print(f"  {hpath}\n  {cpath}")
    return {"grass": grass, "water": water, "gprob": gprob, "wprob": wprob}

def verify(rom, res):
    species = M.const_table(os.path.join(PC, "constants", "pokemon_constants.asm"))
    ok = fail = 0

    def parse_grass(path):
        out, cur = [], None
        for line in open(path, encoding="utf-8"):
            s = line.split(";")[0].strip()
            m = re.match(r"def_grass_wildmons\s+(\w+)", s)
            if m:
                cur = {"map": m.group(1), "rates": [], "mons": []}
                continue
            if cur is None:
                continue
            if s.startswith("end_grass_wildmons"):
                out.append(cur)
                cur = None
                continue
            m = re.match(r"db\s+(\d+)\s+percent,\s*(\d+)\s+percent,\s*(\d+)\s+percent", s)
            if m:
                cur["rates"] = [int(v) for v in m.groups()]
                continue
            m = re.match(r"db\s+(\d+),\s*(\w+)$", s)
            if m:
                cur["mons"].append((int(m.group(1)), m.group(2)))
        return out

    for fname, region in (("johto_grass.asm", "Johto"), ("kanto_grass.asm", "Kanto")):
        want = parse_grass(os.path.join(PC, "data", "wild", fname))
        for w in want:
            got = next((e for e in res["grass"]
                        if e["name"] and e["name"].upper().replace("_", "")
                        == w["map"].replace("_", "")), None)
            if got is None:
                continue

            flat = [x for st in got["sets"] for x in st]
            if len(flat) != len(w["mons"]):
                fail += 1
                print(f"  !! {w['map']}: {len(flat)} slots vs {len(w['mons'])}")
                continue
            for (lv, sp), (wlv, wsp) in zip(flat, w["mons"]):
                if lv == wlv and species.get(wsp) == sp:
                    ok += 1
                else:
                    fail += 1
                    if fail <= 6:
                        print(f"  !! {w['map']}: rom (lv {lv}, sp {sp}) "
                              f"asm (lv {wlv}, {wsp}={species.get(wsp)})")
    print(f"\nverify: {ok} grass slots match the disassembly, {fail} differ")
    return fail == 0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(PC, "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(PC, "pokecrystal.sym"))
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()
    rom = Rom(args.rom, args.sym)
    res = emit(rom)
    if args.verify:
        return 0 if verify(rom, res) else 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
