
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import crystal_maps as M
from crystal_rom import Rom

PC = os.path.join(ROOT, "pokecrystal-master")
BASE_STAT_SIZE = 32
NUM_SPECIES = 251
NAME_LENGTH = 10

def decode_name(raw):
    out = []
    for b in raw:
        if b == 0x50:
            break
        if 0x80 <= b <= 0x99:
            out.append(chr(ord("A") + b - 0x80))
        elif 0xA0 <= b <= 0xB9:
            out.append(chr(ord("a") + b - 0xA0))
        elif b == 0x7F:
            out.append(" ")
        elif b == 0xE1:
            out.append("P")
        elif b == 0xE2:
            out.append("M")
        elif b == 0xE3:
            out.append("-")
        elif b == 0xEF:
            out.append("M")
        elif b == 0xF5:
            out.append("F")
        elif b == 0xE8:
            out.append(".")
        else:
            out.append("")
    return "".join(out)

def read_all(rom):
    bank, addr = rom.addr_of("BaseData")
    nbank, naddr = rom.addr_of("PokemonNames")
    span = naddr - addr
    if span != NUM_SPECIES * BASE_STAT_SIZE:
        raise SystemExit(f"BaseData spans {span} bytes, expected "
                         f"{NUM_SPECIES * BASE_STAT_SIZE} -- wrong ROM?")
    out = []
    for i in range(NUM_SPECIES):
        b = rom.read(bank, addr + i * BASE_STAT_SIZE, BASE_STAT_SIZE)
        name = decode_name(rom.read(nbank, naddr + i * NAME_LENGTH, NAME_LENGTH))
        out.append({
            "dex": i + 1, "name": name,
            "hp": b[1], "atk": b[2], "def": b[3],
            "spd": b[4], "sat": b[5], "sdf": b[6],
            "type1": b[7], "type2": b[8],
            "catch_rate": b[9], "base_exp": b[10],
            "item1": b[11], "item2": b[12],
            "gender": b[13], "hatch_cycles": b[15],
            "pic_dimensions": b[17],
            "growth_rate": b[22],
            "egg1": b[23] >> 4, "egg2": b[23] & 0x0F,
            "tmhm": bytes(b[24:32]),
        })
    return out

def oracle_stats():
    d = os.path.join(PC, "data", "pokemon", "base_stats")
    types = M.const_table(os.path.join(PC, "constants", "type_constants.asm"))
    pokemon = M.const_table(os.path.join(PC, "constants", "pokemon_constants.asm"))
    out = {}
    for fn in os.listdir(d):
        if not fn.endswith(".asm"):
            continue
        txt = open(os.path.join(d, fn), encoding="utf-8", errors="replace").read()
        m = re.search(r"^\s*db\s+(\w+)\s*;\s*(\d+)", txt, re.M)
        if not m:
            continue
        dex = int(m.group(2))
        st = re.search(r"^\s*db\s+(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)",
                       txt, re.M)
        ty = re.search(r"^\s*db\s+(\w+),\s*(\w+)\s*;\s*type", txt, re.M)
        cr = re.search(r"^\s*db\s+(\d+)\s*;\s*catch rate", txt, re.M)
        be = re.search(r"^\s*db\s+(\d+)\s*;\s*base exp", txt, re.M)
        if not (st and ty and cr and be):
            continue
        out[dex] = (tuple(int(x) for x in st.groups())
                    + (types.get(ty.group(1), -1), types.get(ty.group(2), -1),
                       int(cr.group(1)), int(be.group(1))))
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--rom", default=os.path.join(PC, "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(PC, "pokecrystal.sym"))
    args = ap.parse_args()

    rom = Rom(args.rom, args.sym)
    mons = read_all(rom)
    print(f"{len(mons)} species read; "
          f"#1 {mons[0]['name']}, #151 {mons[150]['name']}, "
          f"#251 {mons[250]['name']}")

    if args.verify:
        o = oracle_stats()
        bad, checked = [], 0
        for m in mons:
            want = o.get(m["dex"])
            if want is None:
                continue
            checked += 1
            got = (m["hp"], m["atk"], m["def"], m["spd"], m["sat"], m["sdf"],
                   m["type1"], m["type2"], m["catch_rate"], m["base_exp"])
            if got != want:
                bad.append((m["dex"], m["name"], got, want))
        print(f"verify: {checked - len(bad)}/{checked} species byte-exact "
              f"(stats, types, catch rate, base exp)")
        for d, n, g, w in bad[:6]:
            print(f"  !! #{d} {n}: rom {g} asm {w}")
        if bad:
            print("VERIFY FAILED -- not writing output")
            return 1

    out_dir = os.path.join(ROOT, "generated")
    os.makedirs(out_dir, exist_ok=True)
    banner = ("/* {} -- GENERATED by tools/romimport/extract_crystal_pokedex.py\n"
              " * from pokecrystal.gbc.  The full 251-species Gen 2 database.\n"
              " * ROM-derived: never commit this.\n"
              " */\n")
    with open(os.path.join(out_dir, "gen2_pokedex.h"), "w", newline="\n") as f:
        f.write(banner.format("gen2_pokedex.h"))
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define GEN2_NUM_SPECIES {NUM_SPECIES}\n\n")
        f.write("typedef struct {\n"
                "    const char *name;\n"
                "    uint8_t hp, atk, def, spd, sat, sdf;  /* Gen 2 splits Special */\n"
                "    uint8_t type1, type2;\n"
                "    uint8_t catch_rate, base_exp;\n"
                "    uint8_t item1, item2;\n"
                "    uint8_t gender, hatch_cycles;\n"
                "    uint8_t pic_dimensions;\n"
                "    uint8_t growth_rate;\n"
                "    uint8_t egg1, egg2;\n"
                "    uint8_t tmhm[8];\n"
                "} gen2_base_stats_t;\n\n")
        f.write("/* Indexed by DEX NUMBER - 1. */\n")
        f.write("extern const gen2_base_stats_t gGen2BaseStats[GEN2_NUM_SPECIES];\n")

    with open(os.path.join(out_dir, "gen2_pokedex.c"), "w", newline="\n") as f:
        f.write(banner.format("gen2_pokedex.c"))
        f.write('#include "gen2_pokedex.h"\n\n')
        f.write("const gen2_base_stats_t gGen2BaseStats[GEN2_NUM_SPECIES] = {\n")
        for m in mons:
            tm = ", ".join(f"0x{x:02X}" for x in m["tmhm"])
            f.write(f'    /* {m["dex"]:3d} */ {{ "{m["name"]}", '
                    f'{m["hp"]}, {m["atk"]}, {m["def"]}, {m["spd"]}, '
                    f'{m["sat"]}, {m["sdf"]}, {m["type1"]}, {m["type2"]}, '
                    f'{m["catch_rate"]}, {m["base_exp"]}, {m["item1"]}, '
                    f'{m["item2"]}, {m["gender"]}, {m["hatch_cycles"]}, '
                    f'{m["pic_dimensions"]}, {m["growth_rate"]}, '
                    f'{m["egg1"]}, {m["egg2"]}, {{ {tm} }} }},\n')
        f.write("};\n")
    print(f"wrote {out_dir}\\gen2_pokedex.h / .c")
    return 0

if __name__ == "__main__":
    sys.exit(main())
