
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import crystal_script as CS
from crystal_rom import Rom

OUT = os.path.join(ROOT, "generated")

START_ITEMS = ["POKEDEX", "POKEMON", "PACK", "STATUS", "SAVE",
               "OPTION", "EXIT", "POKEGEAR", "QUIT"]

ITEM_SIZE = 6

NO_EQUIVALENT_FIX = {"<PKMN>": "#MON"}

def read_menu_header(rom, bank, addr):
    return {
        "flags": rom.u8(bank, addr),
        "y1": rom.u8(bank, addr + 1), "x1": rom.u8(bank, addr + 2),
        "y2": rom.u8(bank, addr + 3), "x2": rom.u8(bank, addr + 4),
        "data": rom.u16(bank, addr + 5),
        "default": rom.u8(bank, addr + 7),
    }

def read_menu_data(rom, bank, addr):
    rc = rom.u8(bank, addr + 1)
    return {
        "flags": rom.u8(bank, addr),
        "rows": rc >> 4, "cols": rc & 0x0F,
        "list": rom.u16(bank, addr + 2),
        "string_fn": rom.u16(bank, addr + 4),
        "items": rom.u16(bank, addr + 6),
    }

def extract(rom):
    bank, hdr = rom.sym["StartMenu.MenuHeader"]
    header = read_menu_header(rom, bank, hdr)
    data = read_menu_data(rom, bank, header["data"])

    items = []
    for i, name in enumerate(START_ITEMS):
        a = data["items"] + i * ITEM_SIZE

        s = rom.u16(bank, a + 2)
        d = rom.u16(bank, a + 4)
        items.append({"id": name,
                      "label": text(rom, bank, s),
                      "desc": text(rom, bank, d)})
    return header, data, items

def text(rom, bank, addr):
    raw = CS.read_text(rom, bank, addr)
    if raw is None:
        return ""

    cm = CS.charmap()
    rev = {}
    for b, t in cm.items():
        rev.setdefault(t, b)
    sub = []
    for b in raw:
        fix = NO_EQUIVALENT_FIX.get(cm.get(b))
        if fix is None:
            sub.append(b)
        else:
            sub.extend(rev[ch] for ch in fix)
    s, missing = CS.to_dsl(sub)
    for tok in sorted(missing):
        print(f"  !! {addr:#06x}: no port equivalent for {tok}")

    return s.replace("\\n", "\n")

def cstr(s):
    out = ""
    for ch in s:
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif ch == "\n":
            out += "\\n"
        else:
            out += ch
    return '"' + out + '"'

def emit(header, data, items):
    os.makedirs(OUT, exist_ok=True)
    h = os.path.join(OUT, "crystal_menus.h")
    c = os.path.join(OUT, "crystal_menus.c")

    with open(h, "w", newline="\n") as f:
        f.write(
            "/* crystal_menus.h -- GENERATED by "
            "tools/romimport/extract_crystal_menus.py.  DO NOT EDIT.\n"
            " *\n"
            " * Crystal's start menu, read from the ROM as data: box geometry,\n"
            " * item order, labels and descriptions.  Action pointers are NOT\n"
            " * here -- they are ROM code; the C side binds each item id to this\n"
            " * port's own handler.  ROM-derived: never commit this.\n"
            " *\n"
            " * Descriptions embed '\\n' where the ROM's `next` macro was.\n"
            " * Labels may contain the ROM's own text commands (<PLAYER>,\n"
            " * <POKE>), left as-is for the C side to substitute. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            f"#define CRYSTAL_START_ITEMS {len(items)}\n\n"
            "/* menu_coords from StartMenu.MenuHeader: the box occupies\n"
            " * columns x1..x2 and rows y1..y2 inclusive. */\n"
            "typedef struct {\n"
            "    uint8_t flags, x1, y1, x2, y2, def_selection;\n"
            "    uint8_t data_flags, rows, cols;\n"
            "} crystal_menu_box_t;\n\n"
            "typedef struct {\n"
            "    const char *id;    /* STARTMENUITEM_* name, the ROM's order */\n"
            "    const char *label;\n"
            "    const char *desc;  /* two lines, '\\n' separated */\n"
            "} crystal_menu_item_t;\n\n"
            "extern const crystal_menu_box_t gCrystalStartMenuBox;\n"
            "extern const crystal_menu_item_t "
            "gCrystalStartMenu[CRYSTAL_START_ITEMS];\n")

    with open(c, "w", newline="\n") as f:
        f.write('/* crystal_menus.c -- GENERATED, see the header. */\n'
                '#include "crystal_menus.h"\n\n')
        f.write("const crystal_menu_box_t gCrystalStartMenuBox = {\n"
                f"    0x{header['flags']:02X}, {header['x1']}, {header['y1']}, "
                f"{header['x2']}, {header['y2']}, {header['default']},\n"
                f"    0x{data['flags']:02X}, {data['rows']}, {data['cols']}\n"
                "};\n\n")
        f.write("const crystal_menu_item_t "
                "gCrystalStartMenu[CRYSTAL_START_ITEMS] = {\n")
        for it in items:
            f.write(f"    {{ {cstr(it['id'])}, {cstr(it['label'])}, "
                    f"{cstr(it['desc'])} }},\n")
        f.write("};\n")
    return h, c

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.sym"))
    args = ap.parse_args()

    rom = Rom(args.rom, args.sym)
    header, data, items = extract(rom)
    h, c = emit(header, data, items)
    print(f"start menu box: cols {header['x1']}-{header['x2']} "
          f"rows {header['y1']}-{header['y2']}, "
          f"flags 0x{header['flags']:02X}/0x{data['flags']:02X}, "
          f"default item {header['default']}")
    for it in items:
        print("  {:9s} {:12s} {!r}".format(it["id"], it["label"], it["desc"]))
    print(" ", h)
    print(" ", c)
    return 0

if __name__ == "__main__":
    sys.exit(main())
