
import argparse
import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import crystal_maps as M
from crystal_rom import Rom

PC = os.path.join(ROOT, "pokecrystal-master")
OUT = os.path.join(ROOT, "generated")

TILE_BYTES = 16
ENTRY = 6
WALKING_SPRITE, STANDING_SPRITE, STILL_SPRITE = 1, 2, 3

PORT_TILES = 24

def blob_tiles(stype, declared_bytes):
    tiles = declared_bytes // TILE_BYTES
    return tiles * 2 if stype == WALKING_SPRITE else tiles

def read_sprites(rom):
    b, a = rom.sym["OverworldSprites"]
    end = rom.next_symbol_addr(b, a)
    n = (end - a) // ENTRY if end else 0
    consts = M.const_table(os.path.join(PC, "constants",
                                        "sprite_constants.asm"))
    by_id = {v: k for k, v in consts.items()
             if k.startswith("SPRITE_") and isinstance(v, int)}
    out = []
    for i in range(n):
        e = a + i * ENTRY
        ptr = rom.u16(b, e)
        declared = rom.u8(b, e + 2)
        gbank = rom.u8(b, e + 3)
        stype = rom.u8(b, e + 4)
        pal = rom.u8(b, e + 5)
        tiles = blob_tiles(stype, declared)
        gfx = list(rom.read(gbank, ptr, tiles * TILE_BYTES))
        name = by_id.get(i + 1, f"SPRITE_{i + 1}")
        out.append({"id": i + 1, "name": name, "tiles": tiles, "type": stype,
                    "pal": pal & 7, "gfx": gfx, "ptr": ptr, "bank": gbank})
    return out

def emit(rom):
    sprites = read_sprites(rom)
    os.makedirs(OUT, exist_ok=True)
    hpath = os.path.join(OUT, "crystal_sprites.h")
    cpath = os.path.join(OUT, "crystal_sprites.c")

    with open(hpath, "w", newline="\n") as f:
        f.write("/* crystal_sprites.h -- GENERATED by\n"
                " * tools/romimport/extract_crystal_sprites.py.  DO NOT EDIT.\n"
                " * ROM-derived: never commit this file. */\n"
                "#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define CRYSTAL_NUM_SPRITES {len(sprites)}\n")
        f.write(f"#define CRYSTAL_SPRITE_TILES {PORT_TILES}\n")
        f.write("#define CRYSTAL_SPRITE_GFX_SIZE "
                "(CRYSTAL_SPRITE_TILES * 16)\n\n")
        f.write("/* Same layout as the port's Gen 1 gSpriteGfx: 12 standing\n"
                " * tiles (down/up/left, right mirrors left) then 12 walking.\n"
                " * Sheets shorter than that are zero-padded. */\n"
                "extern const uint8_t gCrystalSpriteGfx"
                "[CRYSTAL_NUM_SPRITES][CRYSTAL_SPRITE_GFX_SIZE];\n"
                "/* Real declared tile count -- 24, 12 or 4.  npc.c gates\n"
                " * facing changes on this the same way it does for Gen 1. */\n"
                "extern const uint8_t gCrystalSpriteTileCount"
                "[CRYSTAL_NUM_SPRITES];\n"
                "/* Default OBJ palette (PAL_OW_*), for an object_event that\n"
                " * names none. */\n"
                "extern const uint8_t gCrystalSpritePal[CRYSTAL_NUM_SPRITES];\n"
                "/* SPRITE_* name minus the prefix, for the DSL to resolve. */\n"
                "extern const char *const gCrystalSpriteNames"
                "[CRYSTAL_NUM_SPRITES];\n"
                "/* OverworldSprites' TYPE byte. Read here all along -- it is\n"
                " * what doubles a WALKING sprite's tile count -- but never\n"
                " * emitted, so the port had no way to ask whether a Crystal\n"
                " * sprite can turn to face you. A STILL sprite has ONE frame;\n"
                " * rotating it indexes facings it does not have. This is the\n"
                " * Crystal-side equivalent of Gen 1's FIRST_STILL_SPRITE ($3D)\n"
                " * cutoff, which means nothing against a Crystal id. */\n"
                "#define CRYSTAL_SPRITE_WALKING  1\n"
                "#define CRYSTAL_SPRITE_STANDING 2\n"
                "#define CRYSTAL_SPRITE_STILL    3\n"
                "extern const uint8_t gCrystalSpriteType[CRYSTAL_NUM_SPRITES];\n")

    with open(cpath, "w", newline="\n") as f:
        f.write("/* crystal_sprites.c -- GENERATED, see the header. */\n"
                '#include "crystal_sprites.h"\n\n')
        f.write("const uint8_t gCrystalSpriteGfx"
                "[CRYSTAL_NUM_SPRITES][CRYSTAL_SPRITE_GFX_SIZE] = {\n")
        for s in sprites:
            f.write(f"    /* {s['id']:3d} {s['name']} "
                    f"({s['tiles']} tiles) */ {{\n")
            data = s["gfx"] + [0] * (PORT_TILES * TILE_BYTES - len(s["gfx"]))
            for t in range(PORT_TILES):
                row = data[t * TILE_BYTES:(t + 1) * TILE_BYTES]
                f.write("        " + ", ".join(f"0x{v:02X}" for v in row) + ",\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("const uint8_t gCrystalSpriteTileCount[CRYSTAL_NUM_SPRITES] = {\n")
        for s in sprites:
            f.write(f"    {s['tiles']},  /* {s['name']} */\n")
        f.write("};\n\n")
        f.write("const uint8_t gCrystalSpritePal[CRYSTAL_NUM_SPRITES] = {\n")
        for s in sprites:
            f.write(f"    {s['pal']},  /* {s['name']} */\n")
        f.write("};\n\n")
        f.write("const char *const gCrystalSpriteNames[CRYSTAL_NUM_SPRITES] = {\n")
        for s in sprites:
            f.write(f'    "{s["name"][len("SPRITE_"):]}",\n')
        f.write("};\n\n")
        f.write("const uint8_t gCrystalSpriteType[CRYSTAL_NUM_SPRITES] = {\n")
        for s in sprites:
            f.write(f"    {s['type']},  /* {s['name']} */\n")
        f.write("};\n")

    kinds = collections.Counter(s["tiles"] for s in sprites)
    print(f"{len(sprites)} sprites: "
          + ", ".join(f"{v} x {k} tiles" for k, v in sorted(kinds.items())))
    print(f"  {hpath}\n  {cpath}")
    return sprites

def verify(rom, sprites):
    try:
        from PIL import Image
    except ImportError:
        print("verify: PIL unavailable, skipped")
        return True

    def png_2bpp(path):
        im = Image.open(path).convert("L")
        w, h = im.size
        px = im.load()
        out = []
        for ty in range(h // 8):
            for tx in range(w // 8):
                for y in range(8):
                    lo = hi = 0
                    for x in range(8):
                        v = (255 - px[tx * 8 + x, ty * 8 + y]) // 85
                        lo |= (v & 1) << (7 - x)
                        hi |= ((v >> 1) & 1) << (7 - x)
                    out += [lo, hi]
        return out

    ok = fail = skipped = length_only = 0
    for s in sprites:

        slug = s["name"][len("SPRITE_"):].lower()
        path = os.path.join(PC, "gfx", "sprites", f"{slug}.png")
        if not os.path.exists(path):
            skipped += 1
            continue

        if Image.open(path).size[0] != 16:
            skipped += 1
            print(f"  -- {s['name']}: {Image.open(path).size[0]}px-wide sheet, "
                  f"tile order not comparable by this oracle")
            continue
        want = png_2bpp(path)
        got = s["gfx"]
        n = min(len(want), len(got))
        same = want[:n] == got[:n]
        if same and len(want) == len(got):
            ok += 1
        elif same:

            length_only += 1
            print(f"  -- {s['name']}: declared {len(got)} B, source art "
                  f"{len(want)} B; the {n} shared bytes match")
        else:
            fail += 1
            if fail <= 6:
                first = next((i for i in range(n) if want[i] != got[i]), n)
                print(f"  !! {s['name']}: rom {len(got)} B, png {len(want)} B"
                      f" -- first difference at byte {first}")
    print(f"\nverify: {ok} sheets byte-identical to the disassembly's PNGs, "
          f"{length_only} match but are declared a different length, "
          f"{fail} genuinely differ, {skipped} had no PNG")
    return fail == 0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(PC, "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(PC, "pokecrystal.sym"))
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()
    rom = Rom(args.rom, args.sym)
    sprites = emit(rom)
    if args.verify:
        return 0 if verify(rom, sprites) else 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
