
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import crystal_script as CS
from crystal_rom import Rom

OUT = os.path.join(ROOT, "generated")

ITEM_NAME_LENGTH = 13

POCKETS = [
    ("Items",    "ItemsPocketMenuHeader"),
    ("KeyItems", "KeyItemsPocketMenuHeader"),
    ("Balls",    "BallsPocketMenuHeader"),
]

TOKEN_FIX = {"<LF>": "\n", "<NEXT>": "\n", "<LINE>": "\n"}

def text(rom, bank, addr):
    raw = CS.read_text(rom, bank, addr)
    if raw is None:
        return ""
    cm = CS.charmap()
    parts, run = "", []

    def flush():
        nonlocal parts, run
        if run:
            s, missing = CS.to_dsl(run)
            for t in sorted(missing):
                print(f"  !! {addr:#06x}: no port equivalent for {t}")
            parts += s
            run = []

    for b in raw:
        tok = cm.get(b)
        if tok in TOKEN_FIX:
            flush()
            parts += TOKEN_FIX[tok]
        else:
            run.append(b)
    flush()
    return parts.replace("\\n", "\n")

def read_pocket(rom, sym):
    bank, a = rom.sym[sym]

    hdr = {"flags": rom.u8(bank, a),
           "y1": rom.u8(bank, a + 1), "x1": rom.u8(bank, a + 2),
           "y2": rom.u8(bank, a + 3), "x2": rom.u8(bank, a + 4),
           "default": rom.u8(bank, a + 7)}
    d = rom.u16(bank, a + 5)
    hdr["data_flags"] = rom.u8(bank, d)
    hdr["rows"] = rom.u8(bank, d + 1)
    hdr["cols"] = rom.u8(bank, d + 2)
    hdr["item_format"] = rom.u8(bank, d + 3)
    return hdr

def read_names(rom, count):
    bank, a = rom.sym["ItemNames"]

    out = []
    off = 0
    for _ in range(count):
        raw = []
        while True:
            b = rom.u8(bank, a + off)
            off += 1
            if b == 0x50:
                break
            raw.append(b)
            if len(raw) > 24:
                break
        s, _missing = CS.to_dsl(raw)
        out.append(s.strip())
    return out, off

PACK_IMG_TILES = 15
PACK_IMG_W, PACK_IMG_H = 5, 3

PACK_MENU_TILES = 0x60
PACK_BG_TILE    = 0x24
PACK_HDR_TILE   = 0x28
PACK_NAME_ROW   = 7
PACK_LIST_COL   = 5

def read_pack_menu_gfx(rom):
    bank, a = rom.sym["PackMenuGFX"]
    return [bytes(rom.u8(bank, a + t * 16 + k) for k in range(16))
            for t in range(PACK_MENU_TILES)]

def read_pack_pals(rom):
    bank, a = rom.sym["_CGB_PackPals.ChrisPackPals"]
    return [[rom.u16(bank, a + p * 8 + c * 2) for c in range(4)]
            for p in range(8)]

def read_pocket_name_tilemap(rom):
    bank, a = rom.sym["DrawPocketName.tilemap"]
    return [[rom.u8(bank, a + p * 15 + i) for i in range(15)] for p in range(4)]

def read_pack_gfx(rom):
    bank, a = rom.sym["PackGFX"]
    imgs = []
    for i in range(4):
        tiles = []
        for t in range(PACK_IMG_TILES):
            base = a + (i * PACK_IMG_TILES + t) * 16
            tiles.append(bytes(rom.u8(bank, base + k) for k in range(16)))
        imgs.append(tiles)

    pb, pa = rom.sym["PackGFXPointers"]
    order = []
    for p in range(4):
        ptr = rom.u16(pb, pa + p * 2)
        order.append((ptr - a) // (PACK_IMG_TILES * 16))
    return imgs, order

def read_descriptions(rom):
    bank, a = rom.sym["ItemDescriptions"]
    first = rom.u16(bank, a)
    count = (first - a) // 2
    out = []
    for i in range(count):
        p = rom.u16(bank, a + i * 2)
        out.append(text(rom, bank, p))
    return out

def cstr(s):
    out = ""
    for ch in s:

        if ord(ch) > 0x7E and ch != "\n":
            continue
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif ch == "\n":
            out += "\\n"
        else:
            out += ch
    return '"' + out + '"'

def emit(pockets, descs, names, imgs, order, menu_gfx, name_map, pals):
    os.makedirs(OUT, exist_ok=True)
    h = os.path.join(OUT, "crystal_pack.h")
    c = os.path.join(OUT, "crystal_pack.c")

    with open(h, "w", newline="\n", encoding="utf-8") as f:
        f.write(
            "/* crystal_pack.h -- GENERATED by "
            "tools/romimport/extract_crystal_pack.py.  DO NOT EDIT.\n"
            " *\n"
            " * Crystal's pack: pocket menu geometry and item descriptions,\n"
            " * read from the ROM.  ROM-derived: never commit.\n"
            " *\n"
            " * Item descriptions have no Gen 1 counterpart -- Gen 1's bag is a\n"
            " * bare list -- so this is a feature, not a reskin. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            "/* Box occupies columns x1..x2, rows y1..y2 inclusive; the list\n"
            " * shows `rows` entries.  item_format is SCROLLINGMENU_ITEMS_*:\n"
            " * QUANTITY draws an 'xN' column, NORMAL does not. */\n"
            "typedef struct {\n"
            "    const char *name;\n"
            "    uint8_t flags, x1, y1, x2, y2, def_selection;\n"
            "    uint8_t data_flags, rows, cols, item_format;\n"
            "} crystal_pocket_t;\n\n"
            f"#define CRYSTAL_NUM_POCKETS {len(pockets)}\n"
            f"#define CRYSTAL_ITEM_DESC_COUNT {len(descs)}\n\n"
            "extern const crystal_pocket_t gCrystalPockets[CRYSTAL_NUM_POCKETS];\n"
            "/* INDEX WITH item_id - 1, NOT item_id.  PrintItemDescription does\n"
            " * `ld a, [wCurSpecies] / dec a` before indexing, because Crystal's\n"
            " * item ids start at 1 (MASTER_BALL) while the table starts at 0.\n"
            " *\n"
            " * AND TMs/HMs NEVER READ THIS TABLE.  PrintItemDescription's first\n"
            " * act is `cp TM01 / jr c, .not_a_tm` -- a TM shows the MOVE's\n"
            " * description via PrintMoveDescription instead, so the entries at\n"
            " * TM ids here are unused filler.  A bag that printed them would\n"
            " * show plausible wrong text rather than nothing.\n"
            " *\n"
            " * Two lines, '\\n' separated. */\n"
            "extern const char *const "
            "gCrystalItemDesc[CRYSTAL_ITEM_DESC_COUNT];\n"
            "/* Crystal's item NAME for the same index.  Present because this\n"
            " * port stores POKERED item ids and the tables above are indexed by\n"
            " * CRYSTAL ids -- they diverge from the second entry (Gen 1\n"
            " * POKE_BALL is 4, Crystal's is 5).  Match on name, never on id. */\n"
            "extern const char *const "
            "gCrystalItemName[CRYSTAL_ITEM_DESC_COUNT];\n\n"
            f"#define CRYSTAL_PACK_IMG_TILES {PACK_IMG_TILES}\n"
            f"#define CRYSTAL_PACK_IMG_W {PACK_IMG_W}\n"
            f"#define CRYSTAL_PACK_IMG_H {PACK_IMG_H}\n"
            "/* Four bag pictures, raw 2bpp, drawn as a 5x3 block at screen\n"
            " * (0,3) -- PlacePackGFX's `hlcoord 0, 3`, 3 rows of 5.\n"
            " *\n"
            " * INDEX WITH gCrystalPackGFXOrder[pocket], NOT the pocket id.\n"
            " * PackGFXPointers shuffles them: image 0 is the KEY ITEM bag, so\n"
            " * storage order would give each pocket a real picture belonging\n"
            " * to a different pocket -- wrong in a way that looks like art. */\n"
            "extern const uint8_t gCrystalPackGFX[4][CRYSTAL_PACK_IMG_TILES][16];\n"
            "extern const uint8_t gCrystalPackGFXOrder[4];\n\n"
            f"#define CRYSTAL_PACK_MENU_TILES 0x{PACK_MENU_TILES:02X}\n"
            f"#define CRYSTAL_PACK_BG_TILE    0x{PACK_BG_TILE:02X}\n"
            f"#define CRYSTAL_PACK_HDR_TILE   0x{PACK_HDR_TILE:02X}\n"
            f"#define CRYSTAL_PACK_NAME_ROW   {PACK_NAME_ROW}\n"
            f"#define CRYSTAL_PACK_LIST_COL   {PACK_LIST_COL}\n"
            "/* The pack SCREEN's tileset -- Pack_InitGFX copies these 96 tiles\n"
            " * to vTiles2, so every tile id below indexes this array:\n"
            " *   $24        background fill, rows 1-11 (blue; pink for Kris)\n"
            " *   $28..$3B   the row-0 header strip, ids run consecutively\n"
            " *   $50..$5E   the bag picture (DrawPackGFX overwrites these)\n"
            " * plus whatever the pocket-name tilemap references. */\n"
            "extern const uint8_t "
            "gCrystalPackMenuGFX[CRYSTAL_PACK_MENU_TILES][16];\n"
            "/* Four 5x3 blocks of tile ids, blitted at (0,7).  The pocket NAME\n"
            " * is art baked into the tileset, not a string. */\n"
            "extern const uint8_t gCrystalPocketNameTilemap[4][15];\n\n"
            "/* The pack screen's BG palettes, BGR555.  _CGB_PackPals assigns\n"
            " * them POSITIONALLY, not per tile:\n"
            " *   (0,0)  1 x 10  -> 1     header, left half\n"
            " *   (10,0) 1 x 10  -> 2     header, right half\n"
            " *   (7,2)  9 x 1   -> 3     the strip down the list's left edge\n"
            " *   (0,7)  3 x 5   -> 4     pocket name\n"
            " *   (0,3)  3 x 5   -> 5     the bag picture\n"
            " * everything else stays palette 0 (WipeAttrmap). */\n"
            "extern const uint16_t gCrystalPackPals[8][4];\n")

    with open(c, "w", newline="\n", encoding="utf-8") as f:
        f.write('/* crystal_pack.c -- GENERATED, see the header. */\n'
                '#include "crystal_pack.h"\n\n')
        f.write("const crystal_pocket_t gCrystalPockets"
                "[CRYSTAL_NUM_POCKETS] = {\n")
        for name, p in pockets:
            f.write(f"    {{ {cstr(name)}, 0x{p['flags']:02X}, "
                    f"{p['x1']}, {p['y1']}, {p['x2']}, {p['y2']}, "
                    f"{p['default']}, 0x{p['data_flags']:02X}, "
                    f"{p['rows']}, {p['cols']}, {p['item_format']} }},\n")
        f.write("};\n\n")
        f.write("const char *const "
                "gCrystalItemDesc[CRYSTAL_ITEM_DESC_COUNT] = {\n")
        for i, d in enumerate(descs):
            f.write(f"    /* {i:3d} */ {cstr(d)},\n")
        f.write("};\n\n")
        f.write("const char *const "
                "gCrystalItemName[CRYSTAL_ITEM_DESC_COUNT] = {\n")
        for i in range(len(descs)):
            nm = names[i] if i < len(names) else ""
            f.write(f"    /* {i:3d} */ {cstr(nm)},\n")
        f.write("};\n\n")
        f.write("const uint8_t gCrystalPackGFX[4]"
                "[CRYSTAL_PACK_IMG_TILES][16] = {\n")
        for i, tiles in enumerate(imgs):
            f.write(f"    /* image {i} */ {{\n")
            for t in tiles:
                f.write("        { " + ", ".join(f"0x{b:02X}" for b in t)
                        + " },\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("const uint8_t gCrystalPackGFXOrder[4] = { "
                + ", ".join(str(o) for o in order) + " };\n\n")
        f.write("const uint8_t "
                "gCrystalPackMenuGFX[CRYSTAL_PACK_MENU_TILES][16] = {\n")
        for i, t in enumerate(menu_gfx):
            f.write(f"    /* ${i:02X} */ {{ "
                    + ", ".join(f"0x{b:02X}" for b in t) + " },\n")
        f.write("};\n\n")
        f.write("const uint8_t gCrystalPocketNameTilemap[4][15] = {\n")
        for p, row in enumerate(name_map):
            f.write(f"    /* pocket {p} */ {{ "
                    + ", ".join(f"0x{b:02X}" for b in row) + " },\n")
        f.write("};\n\n")
        f.write("const uint16_t gCrystalPackPals[8][4] = {\n")
        for i, p in enumerate(pals):
            rgb = "  ".join(f"{v & 31:2d},{(v >> 5) & 31:2d},{(v >> 10) & 31:2d}"
                            for v in p)
            f.write(f"    /* {i} */ {{ "
                    + ", ".join(f"0x{v:04X}" for v in p)
                    + f" }},  /* {rgb} */\n")
        f.write("};\n")
    return h, c

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.sym"))
    args = ap.parse_args()

    rom = Rom(args.rom, args.sym)
    pockets = [(n, read_pocket(rom, s)) for n, s in POCKETS]
    descs = read_descriptions(rom)
    names, width = read_names(rom, len(descs))
    imgs, order = read_pack_gfx(rom)
    menu_gfx = read_pack_menu_gfx(rom)
    name_map = read_pocket_name_tilemap(rom)
    pals = read_pack_pals(rom)
    h, c = emit(pockets, descs, names, imgs, order, menu_gfx, name_map, pals)
    print(f"  names span {width} bytes; pack gfx order (pocket -> image) {order}")
    for n, p in pockets:
        print(f"  {n:9s} cols {p['x1']}-{p['x2']} rows {p['y1']}-{p['y2']}  "
              f"{p['rows']} rows x {p['cols']} cols  fmt {p['item_format']}")
    print(f"  {len(descs)} item descriptions")
    for i in (1, 2, 8):
        if i < len(descs):
            print(f"    item {i}: {descs[i]!r}")
    print(" ", h)
    print(" ", c)
    return 0

if __name__ == "__main__":
    sys.exit(main())
