
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import crystal_script as CS
from crystal_rom import Rom

OUT = os.path.join(ROOT, "generated")

TOKEN_FIX = {"<LF>": "\n"}

VALUE_TABLES = [
    ("TextSpeed",   ["Options_TextSpeed.Fast", "Options_TextSpeed.Mid",
                     "Options_TextSpeed.Slow"]),
    ("BattleScene", ["Options_BattleScene.On", "Options_BattleScene.Off"]),
    ("BattleStyle", ["Options_BattleStyle.Shift", "Options_BattleStyle.Set"]),
    ("Sound",       ["Options_Sound.Mono", "Options_Sound.Stereo"]),
    ("Print",       ["Options_Print.Lightest", "Options_Print.Lighter",
                     "Options_Print.Normal", "Options_Print.Darker",
                     "Options_Print.Darkest"]),
    ("MenuAccount", ["Options_MenuAccount.Off", "Options_MenuAccount.On"]),
]

def text(rom, bank, addr):
    raw = CS.read_text(rom, bank, addr)
    if raw is None:
        return ""
    cm = CS.charmap()
    rev = {}
    for b, t in cm.items():
        rev.setdefault(t, b)
    out = []
    for b in raw:
        tok = cm.get(b)
        if tok in TOKEN_FIX:
            out.append(("LIT", TOKEN_FIX[tok]))
        else:
            out.append(("B", b))

    s = ""
    run = []
    for kind, v in out + [("LIT", "")]:
        if kind == "B":
            run.append(v)
            continue
        if run:
            part, missing = CS.to_dsl(run)
            for t in sorted(missing):
                print(f"  !! {addr:#06x}: no port equivalent for {t}")
            s += part
            run = []
        s += v
    return s.replace("\\n", "\n")

def extract(rom):
    b, a = rom.sym["StringOptions"]
    screen = text(rom, b, a)
    tables = []
    for name, syms in VALUE_TABLES:
        vals = []
        for s in syms:
            if s not in rom.sym:
                print(f"  !! symbol not found: {s}")
                vals.append("")
                continue
            sb, sa = rom.sym[s]
            vals.append(text(rom, sb, sa))
        tables.append((name, vals))
    return screen, tables

def cstr(s):
    out = ""
    for ch in s:
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif ch == "\n":
            out += "\\n"
        else:
            out += ch
    return '"' + out + '"'

def emit(screen, tables):
    os.makedirs(OUT, exist_ok=True)
    h = os.path.join(OUT, "crystal_options.h")
    c = os.path.join(OUT, "crystal_options.c")

    with open(h, "w", newline="\n") as f:
        f.write(
            "/* crystal_options.h -- GENERATED by "
            "tools/romimport/extract_crystal_options.py.  DO NOT EDIT.\n"
            " *\n"
            " * Crystal's OPTIONS screen text, read from the ROM.  Layout is\n"
            " * _Option's own: a full-screen Textbox at (0,0) sized\n"
            " * SCREEN_HEIGHT-2 x SCREEN_WIDTH-2, with StringOptions placed at\n"
            " * (2,2).  Each option is a name line followed by a value line\n"
            " * whose ':' sits at column 10.  ROM-derived: never commit. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            "/* _Option: hlcoord 0,0; b = SCREEN_HEIGHT-2; c = SCREEN_WIDTH-2 */\n"
            "#define CRYSTAL_OPT_BOX_ROWS 16\n"
            "#define CRYSTAL_OPT_BOX_COLS 18\n"
            "/* hlcoord 2, 2 */\n"
            "#define CRYSTAL_OPT_TEXT_COL  2\n"
            "#define CRYSTAL_OPT_TEXT_ROW  2\n\n"
            "/* The whole left column, '\\n' separated, exactly as the ROM\n"
            " * places it -- names and their \"        :\" value lines. */\n"
            "extern const char *const gCrystalOptionsScreen;\n\n")
        for name, vals in tables:
            f.write(f"#define CRYSTAL_OPT_{name.upper()}_COUNT {len(vals)}\n"
                    f"extern const char *const gCrystalOpt{name}"
                    f"[CRYSTAL_OPT_{name.upper()}_COUNT];\n")

    with open(c, "w", newline="\n") as f:
        f.write('/* crystal_options.c -- GENERATED, see the header. */\n'
                '#include "crystal_options.h"\n\n')
        f.write(f"const char *const gCrystalOptionsScreen = {cstr(screen)};\n\n")
        for name, vals in tables:
            f.write(f"const char *const gCrystalOpt{name}"
                    f"[CRYSTAL_OPT_{name.upper()}_COUNT] = {{\n")
            for v in vals:
                f.write(f"    {cstr(v)},\n")
            f.write("};\n\n")
    return h, c

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.sym"))
    args = ap.parse_args()

    rom = Rom(args.rom, args.sym)
    screen, tables = extract(rom)
    h, c = emit(screen, tables)
    print("options screen:")
    for i, line in enumerate(screen.split("\n")):
        print(f"  row {2 + i:2d}  {line!r}")
    for name, vals in tables:
        print(f"  {name:12s} {vals}")
    print(" ", h)
    print(" ", c)
    return 0

if __name__ == "__main__":
    sys.exit(main())
