
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

from crystal_rom import Rom

OUT = os.path.join(ROOT, "generated")

FONT_TILES = 128
FRAME_TILES = 6
TILE_1BPP = 8

def tile_1bpp_to_2bpp(raw):
    out = bytearray()
    for b in raw:
        out.append(b)
        out.append(b)
    return bytes(out)

def read_1bpp(rom, bank, addr, ntiles):
    return [tile_1bpp_to_2bpp(
                bytes(rom.u8(bank, addr + t * TILE_1BPP + i) for i in range(TILE_1BPP)))
            for t in range(ntiles)]

FONT_BATTLE_EXTRA_TILES = 25

def read_battle_extra(rom):
    bank, a = rom.sym["FontBattleExtra"]
    return [bytes(rom.u8(bank, a + t * 16 + k) for k in range(16))
            for t in range(FONT_BATTLE_EXTRA_TILES)]

def num_frames(rom):
    bank, addr = rom.sym["Frames"]
    end = rom.next_symbol_addr(bank, addr)
    if not end:
        return 8
    return (end - addr) // (FRAME_TILES * TILE_1BPP)

def extract(rom):
    fb, fa = rom.sym["Font"]
    font = read_1bpp(rom, fb, fa, FONT_TILES)

    nfr = num_frames(rom)
    rb, ra = rom.sym["Frames"]
    frames = [read_1bpp(rom, rb, ra + f * FRAME_TILES * TILE_1BPP, FRAME_TILES)
              for f in range(nfr)]

    sb, sa = rom.sym["TextboxSpaceGFX"]
    space = read_1bpp(rom, sb, sa, 1)[0]
    extra = read_battle_extra(rom)
    return font, frames, space, extra

def carr(tile):
    return "{ " + ", ".join(f"0x{b:02X}" for b in tile) + " }"

def emit(font, frames, space, extra):
    os.makedirs(OUT, exist_ok=True)
    h = os.path.join(OUT, "crystal_font.h")
    c = os.path.join(OUT, "crystal_font.c")
    nfr = len(frames)

    with open(h, "w", newline="\n") as f:
        f.write(
            "/* crystal_font.h -- GENERATED by "
            "tools/romimport/extract_crystal_font.py.  DO NOT EDIT.\n"
            " *\n"
            " * Crystal's text font and textbox frames, decompressed from the\n"
            " * user's own ROM.  ROM-derived: never commit this.\n"
            " *\n"
            " * Already expanded 1bpp -> 2bpp the way the hardware does it, so\n"
            " * these drop straight into Display_LoadTile.  The slot layout is\n"
            " * the one src/data/font_data.h already uses -- glyph i is\n"
            " * character $80+i, frame tile i is character $79+i -- because the\n"
            " * two engines happen to agree exactly.  See the extractor. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            f"#define CRYSTAL_FONT_TILES  {FONT_TILES}\n"
            f"#define CRYSTAL_FRAME_TILES {FRAME_TILES}\n"
            f"#define CRYSTAL_NUM_FRAMES  {nfr}\n\n"
            "/* Character $80 + i. */\n"
            "extern const uint8_t gCrystalFont[CRYSTAL_FONT_TILES][16];\n"
            "/* [frame][tile], tile i is character $79 + i: the six box-drawing\n"
            " * glyphs.  The player picks the frame in Crystal's options menu\n"
            " * (wTextboxFrame, bits 0-2), so all of them are real choices. */\n"
            "extern const uint8_t gCrystalFrames"
            "[CRYSTAL_NUM_FRAMES][CRYSTAL_FRAME_TILES][16];\n"
            "/* Character $7F.  A textbox-interior space, which is NOT the same\n"
            " * tile as a blank map tile -- LoadFrame reloads it per frame. */\n"
            "extern const uint8_t gCrystalTextboxSpace[16];\n\n"
            f"#define CRYSTAL_BATTLE_EXTRA_TILES {FONT_BATTLE_EXTRA_TILES}\n"
            "/* FontBattleExtra: character $60 + i.  The HP-bar segments and\n"
            " * HUD glyphs -- LoadPartyMenuGFX loads these before anything else,\n"
            " * so the party menu's HP bars are drawn from HERE, not from the\n"
            " * main font.  Already 2bpp in the ROM (Get2bppViaHDMA), so unlike\n"
            " * gCrystalFont there is no 1bpp plane duplication. */\n"
            "extern const uint8_t "
            "gCrystalBattleExtra[CRYSTAL_BATTLE_EXTRA_TILES][16];\n")

    with open(c, "w", newline="\n") as f:
        f.write('/* crystal_font.c -- GENERATED, see the header. */\n'
                '#include "crystal_font.h"\n\n')
        f.write("const uint8_t gCrystalFont[CRYSTAL_FONT_TILES][16] = {\n")
        for i, t in enumerate(font):
            f.write(f"    /* ${0x80 + i:02X} */ {carr(t)},\n")
        f.write("};\n\n")
        f.write("const uint8_t gCrystalFrames"
                "[CRYSTAL_NUM_FRAMES][CRYSTAL_FRAME_TILES][16] = {\n")
        for fi, fr in enumerate(frames):
            f.write(f"    /* frame {fi} */ {{\n")
            for ti, t in enumerate(fr):
                f.write(f"        /* ${0x79 + ti:02X} */ {carr(t)},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write(f"const uint8_t gCrystalTextboxSpace[16] = {carr(space)};\n\n")
        f.write("const uint8_t "
                "gCrystalBattleExtra[CRYSTAL_BATTLE_EXTRA_TILES][16] = {\n")
        for i, t in enumerate(extra):
            f.write(f"    /* ${0x60 + i:02X} */ {carr(t)},\n")
        f.write("};\n")
    return h, c

def verify(font, frames, space):
    src = os.path.join(ROOT, "pokecrystal-master", "gfx", "font")
    frm = os.path.join(ROOT, "pokecrystal-master", "gfx", "frames")
    ok = bad = skipped = 0

    def cmp1bpp(path, tiles, label):
        nonlocal ok, bad, skipped
        if not os.path.isfile(path):
            skipped += 1
            print(f"  -- {label}: no {os.path.basename(path)} to compare")
            return
        raw = open(path, "rb").read()
        for i, t in enumerate(tiles):
            want = tile_1bpp_to_2bpp(raw[i * TILE_1BPP:(i + 1) * TILE_1BPP])
            if bytes(t) == want:
                ok += 1
            else:
                bad += 1
                if bad <= 5:
                    print(f"  !! {label} tile {i} differs")

    cmp1bpp(os.path.join(src, "font.1bpp"), font, "Font")
    for fi, fr in enumerate(frames):
        cmp1bpp(os.path.join(frm, f"{fi + 1}.1bpp"), fr, f"frame {fi}")
    print(f"\nfont/frames verify: {ok} tiles identical, {bad} differ, "
          f"{skipped} files not present")
    return bad == 0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(ROOT, "pokecrystal-master",
                                                  "pokecrystal.sym"))
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()

    rom = Rom(args.rom, args.sym)
    font, frames, space, extra = extract(rom)
    h, c = emit(font, frames, space, extra)
    print(f"{len(font)} font tiles, {len(frames)} textbox frames "
          f"x {FRAME_TILES} tiles, 1 space tile")
    print(" ", h)
    print(" ", c)
    if args.verify and not verify(font, frames, space):
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
