
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import crystal_maps as M
from crystal_rom import Rom

PC = os.path.join(ROOT, "pokecrystal-master")
OUT = os.path.join(ROOT, "generated")

EMOTE_LENGTH = 6
TILE_BYTES = 16
VTILES0 = 0x8000

GRASS_FACINGS = ("FacingGrass1", "FacingGrass2")
PAL_OW_TREE = 6

def emote_names(pc_dir):
    out, on = [], False
    path = os.path.join(pc_dir, "constants", "script_constants.asm")
    for line in open(path, encoding="utf-8"):
        s = line.split(";")[0].strip()
        if s.startswith("const EMOTE_"):
            out.append(s.split()[1])
            on = True
        elif on and s.startswith("DEF NUM_EMOTES"):
            break
    return out

def read_emotes(rom):
    bank, addr = rom.addr_of("Emotes")
    end = rom.next_symbol_addr(bank, addr)
    n = ((end - addr) // EMOTE_LENGTH) if end else 0
    names = emote_names(PC)
    out = []
    for i in range(n):
        a = addr + i * EMOTE_LENGTH
        ptr = rom.u16(bank, a)
        nbytes = rom.u8(bank, a + 2)
        gbank = rom.u8(bank, a + 3)
        dest = rom.u16(bank, a + 4)
        sym = sorted((s for s in rom.names_at(gbank, ptr)), key=len)
        out.append({
            "id": i,
            "name": names[i] if i < len(names) else f"EMOTE_{i}",
            "symbol": sym[0] if sym else None,
            "bank": gbank, "ptr": ptr,
            "bytes": nbytes,
            "tiles": nbytes // TILE_BYTES,

            "dest_tile": (dest - VTILES0) // TILE_BYTES,
            "gfx": list(rom.read(gbank, ptr, nbytes)),
        })
    return out

def read_facing(rom, sym):
    bank, addr = rom.sym[sym]
    n = rom.u8(bank, addr)
    ents = []
    for i in range(n):
        a = addr + 1 + i * 4
        y, x = rom.u8(bank, a), rom.u8(bank, a + 1)
        ents.append((y - 256 if y >= 128 else y,
                     x - 256 if x >= 128 else x,
                     rom.u8(bank, a + 2), rom.u8(bank, a + 3)))
    return ents

def emit(rom):
    emotes = read_emotes(rom)
    facings = {s: read_facing(rom, s) for s in GRASS_FACINGS}
    rustle = next((e for e in emotes if e["name"] == "EMOTE_GRASS_RUSTLE"), None)
    if rustle is None:
        sys.exit("Emotes table has no EMOTE_GRASS_RUSTLE entry")

    os.makedirs(OUT, exist_ok=True)
    hpath = os.path.join(OUT, "crystal_emotes.h")
    cpath = os.path.join(OUT, "crystal_emotes.c")

    nfr = len(GRASS_FACINGS)
    nobj = max(len(v) for v in facings.values())

    with open(hpath, "w", newline="\n") as f:
        f.write("/* crystal_emotes.h -- GENERATED by\n"
                " * tools/romimport/extract_crystal_emotes.py.  DO NOT EDIT.\n"
                " * ROM-derived: never commit this file. */\n"
                "#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define CRYSTAL_NUM_EMOTES {len(emotes)}\n")
        f.write(f"#define CRYSTAL_EMOTE_MAX_BYTES "
                f"{max(e['bytes'] for e in emotes)}\n\n")
        f.write("typedef struct {\n"
                "    const char *name;\n"
                "    uint8_t     tiles;      /* declared length / 16 */\n"
                "    uint8_t     dest_tile;  /* VRAM tile the ROM loads it to */\n"
                "    uint16_t    bytes;\n"
                "    const uint8_t *gfx;\n"
                "} crystal_emote_t;\n\n")
        f.write("extern const crystal_emote_t gCrystalEmotes[CRYSTAL_NUM_EMOTES];\n\n")
        f.write("/* ---- grass rustle ------------------------------------------\n"
                " * The single 8x8 tile ShakeGrass draws, and the two OAM\n"
                " * layouts SetFacingGrassShake alternates between.  See the\n"
                " * extractor's docstring: the frames differ by one pixel of\n"
                " * splay, which is the entire animation. */\n")
        f.write(f"#define CRYSTAL_GRASS_RUSTLE_FRAMES {nfr}\n")
        f.write(f"#define CRYSTAL_GRASS_RUSTLE_OBJS {nobj}\n")
        f.write("/* SetFacingGrassShake: `inc [hl]` then `and 4` -- so the frame\n"
                " * flips every FOUR ticks, not every tick. */\n"
                "#define CRYSTAL_GRASS_RUSTLE_FRAME_MASK 4\n")
        f.write(f"#define CRYSTAL_GRASS_RUSTLE_PAL {PAL_OW_TREE}  /* PAL_OW_TREE */\n\n")
        f.write("typedef struct { int8_t y, x; uint8_t attr, tile; } crystal_oam_t;\n\n")
        f.write("extern const uint8_t gCrystalGrassRustleGfx[16];\n")
        f.write("extern const crystal_oam_t gCrystalGrassRustleOam"
                "[CRYSTAL_GRASS_RUSTLE_FRAMES][CRYSTAL_GRASS_RUSTLE_OBJS];\n")

    with open(cpath, "w", newline="\n") as f:
        f.write("/* crystal_emotes.c -- GENERATED, see the header. */\n"
                '#include "crystal_emotes.h"\n\n')
        for e in emotes:
            f.write(f"static const uint8_t s_gfx_{e['id']}[] = {{ "
                    + ", ".join(f"0x{v:02X}" for v in e["gfx"]) + " };\n")
        f.write("\nconst crystal_emote_t gCrystalEmotes[CRYSTAL_NUM_EMOTES] = {\n")
        for e in emotes:
            f.write(f'    {{ "{e["name"]}", {e["tiles"]}, 0x{e["dest_tile"]:02X}, '
                    f'{e["bytes"]}, s_gfx_{e["id"]} }},'
                    f'  /* {e["symbol"] or "?"} */\n')
        f.write("};\n\n")
        f.write("const uint8_t gCrystalGrassRustleGfx[16] = {\n    "
                + ", ".join(f"0x{v:02X}" for v in rustle["gfx"][:16]) + "\n};\n\n")
        f.write("const crystal_oam_t gCrystalGrassRustleOam"
                "[CRYSTAL_GRASS_RUSTLE_FRAMES][CRYSTAL_GRASS_RUSTLE_OBJS] = {\n")
        for s in GRASS_FACINGS:
            ents = facings[s]
            f.write(f"    /* {s} */ {{ "
                    + ", ".join(f"{{ {y}, {x}, 0x{at:02X}, 0x{ti:02X} }}"
                                for y, x, at, ti in ents)
                    + " },\n")
        f.write("};\n")

    print(f"{len(emotes)} emotes; grass rustle: {rustle['tiles']} tile "
          f"(${rustle['dest_tile']:02X}), {nfr} facings x {nobj} objects")
    for s in GRASS_FACINGS:
        print(f"  {s}: " + "  ".join(f"(y={y},x={x},attr=${a:02X},tile=${t:02X})"
                                     for y, x, a, t in facings[s]))
    print(f"  {hpath}\n  {cpath}")
    return {"emotes": emotes, "facings": facings}

def verify(rom, res):
    ok = fail = 0

    try:
        from PIL import Image
    except ImportError:
        Image = None
        print("verify: PIL unavailable, graphics not compared")

    if Image is not None:
        for e in res["emotes"]:
            sym = e["symbol"] or ""

            slug = sym[:-3].lower() if sym.endswith("GFX") else None
            if not slug:
                slug = e["name"][len("EMOTE_"):].lower()
            cand = [os.path.join(PC, "gfx", "overworld", f"{slug}.png"),
                    os.path.join(PC, "gfx", "emotes", f"{slug}.png")]
            path = next((p for p in cand if os.path.exists(p)), None)
            if path is None:
                continue
            im = Image.open(path).convert("L")
            w, h = im.size
            px = im.load()
            want = []
            for ty in range(h // 8):
                for tx in range(w // 8):
                    for y in range(8):
                        lo = hi = 0
                        for x in range(8):
                            v = (255 - px[tx * 8 + x, ty * 8 + y]) // 85
                            lo |= (v & 1) << (7 - x)
                            hi |= ((v >> 1) & 1) << (7 - x)
                        want += [lo, hi]
            n = min(len(want), len(e["gfx"]))
            if want[:n] == e["gfx"][:n] and n > 0:
                ok += 1
            else:
                fail += 1
                print(f"  !! {e['name']}: {len(e['gfx'])} B from rom vs "
                      f"{len(want)} B from {os.path.basename(path)}")

    src = open(os.path.join(PC, "data", "sprites", "facings.asm"),
               encoding="utf-8").read()
    consts = M.const_table(os.path.join(PC, "constants",
                                        "map_object_constants.asm"))
    for sym, ents in res["facings"].items():
        block = src.split(f"\n{sym}:", 1)
        if len(block) < 2:
            continue
        want = []
        for line in block[1].splitlines()[1:]:
            s = line.split(";")[0].strip()
            if not s:
                continue
            if not s.startswith("db "):
                break
            parts = [p.strip() for p in s[3:].split(",")]
            if len(parts) != 4:
                break

            def val(tok):
                tok = tok.strip()
                if tok.startswith("$"):
                    return int(tok[1:], 16)
                if re.fullmatch(r"-?\d+", tok):
                    return int(tok)

                v = 0
                for piece in tok.split("|"):
                    v |= consts.get(piece.strip(), 0)
                return v
            want.append((val(parts[0]), val(parts[1]),
                         val(parts[2]), val(parts[3])))
        if want and want == ents:
            ok += 1
        elif want:
            fail += 1
            print(f"  !! {sym}: rom {ents} vs asm {want}")

    print(f"\nverify: {ok} emote graphics + facing layouts match the "
          f"disassembly, {fail} differ")
    return fail == 0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(PC, "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(PC, "pokecrystal.sym"))
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()
    rom = Rom(args.rom, args.sym)
    res = emit(rom)
    if args.verify:
        return 0 if verify(rom, res) else 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
