
import argparse
import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import crystal_maps as M
from crystal_rom import Rom

PC = os.path.join(ROOT, "pokecrystal-master")
OUT = os.path.join(ROOT, "generated")

VTILES2 = 0x9000
TILE_BYTES = 16

FIXED_FRAMES = {
    "water":       ("AnimateWaterTile.WaterTileFrames", 4),
    "flower":      ("AnimateFlowerTile.FlowerTileFrames", 4),
    "lava":        ("LavaBubbleTileFrames", 4),
    "forest_left": ("ForestTreeLeftFrames", 2),
    "forest_right": ("ForestTreeRightFrames", 2),
}

def arg_kind(arg):
    if 0x8000 <= arg < 0xA000:
        return "vram"
    if 0xC000 <= arg < 0xE000:
        return "wram"
    if 0x4000 <= arg < 0x8000:
        return "romptr"
    return "none"

def read_descriptor(rom, bank, addr, nframes):
    dest = rom.u16(bank, addr)
    src = rom.u16(bank, addr + 2)
    tiles = [list(rom.read(bank, src + i * TILE_BYTES, TILE_BYTES))
             for i in range(nframes)]
    return dest, src, tiles

def emit(rom):
    bank = M.anim_bank(rom)
    consts = M.const_table(os.path.join(PC, "constants",
                                        "tileset_constants.asm"))
    tsids = {n: v for n, v in consts.items()
             if n.startswith("TILESET_") and not n.endswith("_LENGTH")
             and isinstance(v, int)}

    scripts = {}
    per_ts = {}
    for name, tsid in sorted(tsids.items(), key=lambda kv: kv[1]):
        ts = M.read_tileset_entry(rom, tsid)
        ab, aa = ts["anim"]
        names = rom.names_at(ab, aa)
        label = names[0] if names else f"Anim_{aa:04X}"
        per_ts[name] = (tsid, label)
        if label not in scripts:
            scripts[label] = M.read_tileset_anim(rom, ab, aa)

    routines = sorted({r for fr in scripts.values() for r, _a in fr})

    frames_for = {"AnimateTowerPillarTile": 5, "AnimateWhirlpoolTile": 4}
    descriptors = {}
    for fr in scripts.values():
        for routine, arg in fr:
            if arg_kind(arg) == "romptr" and routine in frames_for:
                if arg not in descriptors:
                    descriptors[arg] = read_descriptor(rom, bank, arg,
                                                       frames_for[routine])

    fixed = {}
    for key, (sym, n) in FIXED_FRAMES.items():
        if sym not in rom.sym:
            continue
        b, a = rom.sym[sym]
        fixed[key] = [list(rom.read(b, a + i * TILE_BYTES, TILE_BYTES))
                      for i in range(n)]

    pillar_seq = []
    if "AnimateTowerPillarTile.TowerPillarTileFrameOffsets" in rom.sym:
        b, a = rom.sym["AnimateTowerPillarTile.TowerPillarTileFrameOffsets"]
        pillar_seq = [rom.u8(b, a + i) // TILE_BYTES for i in range(8)]

    fountain = []
    if "AnimateFountainTile.FountainTileFramePointers" in rom.sym:
        b, a = rom.sym["AnimateFountainTile.FountainTileFramePointers"]
        for i in range(8):
            p = rom.u16(b, a + i * 2)
            fountain.append(list(rom.read(b, p, TILE_BYTES)))

    os.makedirs(OUT, exist_ok=True)
    hpath = os.path.join(OUT, "crystal_tile_anims.h")
    cpath = os.path.join(OUT, "crystal_tile_anims.c")

    order = sorted(scripts)
    script_index = {lab: i for i, lab in enumerate(order)}

    with open(hpath, "w", newline="\n") as f:
        f.write("/* crystal_tile_anims.h -- GENERATED by\n"
                " * tools/romimport/extract_crystal_tile_anims.py.  DO NOT EDIT.\n"
                " * ROM-derived: never commit this file. */\n"
                "#pragma once\n#include <stdint.h>\n\n")
        f.write("/* The routines the ROM's scripts actually reference.  Derived\n"
                " * from the symbol each `tileframe` function address resolves\n"
                " * to, so this list is the ROM's, not a chosen subset. */\n"
                "typedef enum {\n")
        for i, r in enumerate(routines):
            f.write(f"    CRYSTAL_ANIM_{_up(r)} = {i},\n")
        f.write(f"    CRYSTAL_ANIM_COUNT = {len(routines)}\n"
                "}} crystal_anim_routine_t;\n".replace("}}", "}"))
        f.write("\ntypedef struct {\n"
                "    uint8_t  routine;   /* crystal_anim_routine_t */\n"
                "    uint8_t  arg_kind;  /* 0 none, 1 vram tile, 2 wram buffer,\n"
                "                         * 3 resolved descriptor index */\n"
                "    uint16_t arg;       /* vram TILE INDEX, or descriptor index,\n"
                "                         * or the raw value for wram */\n"
                "} crystal_anim_frame_t;\n\n")
        f.write("typedef struct {\n"
                "    uint16_t first;     /* index into gCrystalAnimFrames */\n"
                "    uint8_t  count;     /* frames, including DoneTileAnimation */\n"
                "} crystal_anim_script_t;\n\n")
        f.write("/* A whirlpool/pillar descriptor the ROM reached through a\n"
                " * pointer argument, resolved so the engine never chases one. */\n"
                "typedef struct {\n"
                "    uint16_t dest_tile;     /* VRAM tile index */\n"
                "    uint8_t  num_frames;\n"
                "    uint8_t  frames[8][16];\n"
                "} crystal_anim_descriptor_t;\n\n")
        f.write(f"#define CRYSTAL_ANIM_NUM_SCRIPTS {len(order)}\n")
        f.write(f"#define CRYSTAL_ANIM_NUM_FRAMES "
                f"{sum(len(scripts[l]) for l in order)}\n")
        f.write(f"#define CRYSTAL_ANIM_NUM_DESCRIPTORS {len(descriptors)}\n")
        f.write(f"#define CRYSTAL_NUM_TILESETS {max(tsids.values()) + 1}\n\n")
        for i, lab in enumerate(order):
            f.write(f"#define CRYSTAL_ANIM_SCRIPT_{_up(lab)} {i}\n")
        f.write("\nextern const crystal_anim_frame_t "
                "gCrystalAnimFrames[CRYSTAL_ANIM_NUM_FRAMES];\n"
                "extern const crystal_anim_script_t "
                "gCrystalAnimScripts[CRYSTAL_ANIM_NUM_SCRIPTS];\n"
                "/* tileset id -> script index */\n"
                "extern const uint8_t "
                "gCrystalTilesetAnim[CRYSTAL_NUM_TILESETS];\n"
                "extern const crystal_anim_descriptor_t "
                "gCrystalAnimDescriptors[CRYSTAL_ANIM_NUM_DESCRIPTORS];\n\n")
        for key in sorted(fixed):
            f.write(f"#define CRYSTAL_ANIM_{key.upper()}_FRAMES {len(fixed[key])}\n")
            f.write(f"extern const uint8_t gCrystalAnim{_camel(key)}"
                    f"[{len(fixed[key])}][16];\n")
        if fountain:
            f.write(f"#define CRYSTAL_ANIM_FOUNTAIN_FRAMES {len(fountain)}\n")
            f.write(f"extern const uint8_t gCrystalAnimFountain"
                    f"[{len(fountain)}][16];\n")
        if pillar_seq:
            f.write("/* AnimateTowerPillarTile's own frame order, indexed by\n"
                    " * wTileAnimationTimer & 7 -- a ping-pong, not 0..7. */\n"
                    "extern const uint8_t gCrystalAnimPillarSeq[8];\n")

    desc_index = {arg: i for i, arg in enumerate(sorted(descriptors))}

    with open(cpath, "w", newline="\n") as f:
        f.write("/* crystal_tile_anims.c -- GENERATED, see the header. */\n"
                '#include "crystal_tile_anims.h"\n\n')
        f.write("const crystal_anim_frame_t "
                "gCrystalAnimFrames[CRYSTAL_ANIM_NUM_FRAMES] = {\n")
        first = {}
        n = 0
        for lab in order:
            first[lab] = n
            f.write(f"    /* ---- {lab} ---- */\n")
            for routine, arg in scripts[lab]:
                k = arg_kind(arg)
                if k == "vram":
                    kind, val = 1, (arg - VTILES2) // TILE_BYTES
                elif k == "wram":
                    kind, val = 2, arg
                elif k == "romptr" and arg in desc_index:
                    kind, val = 3, desc_index[arg]
                else:
                    kind, val = 0, 0
                f.write(f"    {{ CRYSTAL_ANIM_{_up(routine)}, {kind}, {val} }},\n")
                n += 1
        f.write("};\n\n")
        f.write("const crystal_anim_script_t "
                "gCrystalAnimScripts[CRYSTAL_ANIM_NUM_SCRIPTS] = {\n")
        for lab in order:
            f.write(f"    {{ {first[lab]}, {len(scripts[lab])} }},"
                    f"  /* {lab} */\n")
        f.write("};\n\n")
        f.write(f"const uint8_t gCrystalTilesetAnim[CRYSTAL_NUM_TILESETS] = {{\n")
        by_id = {v: k for k, v in tsids.items()}
        for tsid in range(max(tsids.values()) + 1):
            nm = by_id.get(tsid)
            idx = script_index[per_ts[nm][1]] if nm else 0
            f.write(f"    {idx},  /* {tsid:2d} {nm or '?'} */\n")
        f.write("};\n\n")
        f.write("const crystal_anim_descriptor_t "
                "gCrystalAnimDescriptors[CRYSTAL_ANIM_NUM_DESCRIPTORS] = {\n")
        for arg in sorted(descriptors):
            dest, src, tiles = descriptors[arg]
            f.write(f"    /* ${arg:04X} -> dest ${dest:04X} src ${src:04X} */\n"
                    f"    {{ {(dest - VTILES2) // TILE_BYTES}, {len(tiles)}, {{\n")
            for t in tiles:
                f.write("        { " + ", ".join(f"0x{b:02X}" for b in t) + " },\n")
            for _ in range(8 - len(tiles)):
                f.write("        { 0 },\n")
            f.write("    } },\n")
        f.write("};\n\n")
        for key in sorted(fixed):
            f.write(f"const uint8_t gCrystalAnim{_camel(key)}"
                    f"[{len(fixed[key])}][16] = {{\n")
            for t in fixed[key]:
                f.write("    { " + ", ".join(f"0x{b:02X}" for b in t) + " },\n")
            f.write("};\n\n")
        if fountain:
            f.write(f"const uint8_t gCrystalAnimFountain[{len(fountain)}][16] = {{\n")
            for t in fountain:
                f.write("    { " + ", ".join(f"0x{b:02X}" for b in t) + " },\n")
            f.write("};\n\n")
        if pillar_seq:
            f.write("const uint8_t gCrystalAnimPillarSeq[8] = { "
                    + ", ".join(str(v) for v in pillar_seq) + " };\n")

    print(f"{len(order)} scripts, {sum(len(scripts[l]) for l in order)} frames, "
          f"{len(routines)} routines, {len(descriptors)} descriptors, "
          f"{len(fixed)} fixed frame sets"
          + (f", fountain {len(fountain)}" if fountain else ""))
    print(f"  {hpath}\n  {cpath}")
    return {"scripts": scripts, "per_ts": per_ts, "routines": routines,
            "descriptors": descriptors}

def _up(s):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", s).upper().replace(".", "_")

def _camel(s):
    return "".join(p.capitalize() for p in s.split("_"))

def verify(rom, res):
    src = open(os.path.join(PC, "data", "tileset_anims.asm"),
               encoding="utf-8").read()

    blocks, labels = {}, []
    for line in src.splitlines():
        s = line.split(";")[0].strip()
        m = re.match(r"^(\w+):$", s)
        if m:
            labels.append(m.group(1))
            continue
        m = re.match(r"^tileframe\s+(\w+)", s)
        if m:
            for lab in labels:
                blocks.setdefault(lab, []).append(m.group(1))
            if m.group(1) == "DoneTileAnimation":
                labels = []
            continue
    ok = fail = 0
    checked = 0
    for lab, frames in sorted(res["scripts"].items()):
        want = blocks.get(lab)
        if want is None:
            continue
        checked += 1
        got = [r for r, _a in frames]
        if got == want:
            ok += len(got)
        else:
            fail += 1
            print(f"  !! {lab}\n     asm: {want}\n     rom: {got}")
    print(f"\nverify: {checked} scripts checked, {ok} frames match, "
          f"{fail} scripts differ")
    return fail == 0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=os.path.join(PC, "pokecrystal.gbc"))
    ap.add_argument("--sym", default=os.path.join(PC, "pokecrystal.sym"))
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()
    rom = Rom(args.rom, args.sym)
    res = emit(rom)
    if args.verify:
        return 0 if verify(rom, res) else 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
